/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main_ftprintf.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: angkim <angkim@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/02/05 10:09:25 by ashanbha          #+#    #+#             */
/*   Updated: 2019/10/06 16:13:31 by angkim           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"
#include <stdio.h>
#include <limits.h>
#include <stdlib.h>

int	main(void)
{
	// float	b;
	// // float	d;
	// long double ld_b;
	// char	c;
	// char	*str;
	// int		a;
	// unsigned short ushort_a;
	// unsigned char uchar_a;
	// unsigned long ulong_a;
	// unsigned long long ullong_a;
	// short short_a;
	// signed char signchar_a;
	// long long_a;
	// long long llong_a;

	// a = (int)1234567;
	// ushort_a = (unsigned short)123;
	// uchar_a = (unsigned char)'g';
	// ulong_a = (unsigned long)1234566789013123L;
	// ullong_a = (unsigned long long)123456678902312313ULL;
	// short_a = (short)-123;
	// signchar_a = (signed char)'g';
	// long_a = (long)-1234566789013123L;
	// llong_a = (long long)-123456678902312313ULL;
	// b = 65.99999;
	// c = 'b';
	// ld_b = 5.5767458458;
	// str = "Hello World This Is Probably Long Enough";

	//  int i = INT_MAX;
	//  long l = i * 4;
	//  long long ll = i * 8;


// >>>> 93_conv_f.spec.c ------------ [FAIL] BBBB [BUS!] simple_small_nbr -> (null)
	// ft_printf("{%f}{%lf}{%Lf}\n", 1.42, 1.42, 1.42l);	
	// printf("{%f}{%lf}{%Lf}\n", 1.42, 1.42, 1.42l);


	ft_printf("%f\n", (double)INT_MIN - 1);
	printf("%f\n", (double)INT_MIN - 1);

	// ft_printf("{%f}\n", 123.45);

    // printf("   printf: d, hd, hhd, ld, lld, +020hhd9 '<%d> <%hd> <%hhd> <%ld> <%lld> <%+020.9hhd>'\n", a, short_a, signchar_a, long_a, llong_a, signchar_a);
    // ft_printf("ft_printf: d, hd, hhd, ld, lld, +020hhd9 '<%d> <%hd> <%hhd> <%ld> <%lld> <%+020.9hhd>'\n", a, short_a, signchar_a, long_a, llong_a, signchar_a);
	// printf("   printf: c, s, p '<%c> <%s> <%p>'\n", c, str, &a);
	// ft_printf("ft_printf: c, s, p '<%c> <%s> <%p>'\n", c, str, &a);
	// printf("   printf: o, #o, ho, hho, lo, llo '<%o> <%#o> <%ho> <%hho> <%lo> <%llo>'\n", a, a, ushort_a, uchar_a, ulong_a, ullong_a);
    // ft_printf("ft_printf: o, #o, ho, hho, lo, llo '<%o> <%#o> <%ho> <%hho> <%lo> <%llo>'\n", a, a, ushort_a, uchar_a, ulong_a, ullong_a);
    // printf("   printf: u, hu, hhu, lu, llu '<%u> <%hu> <%hhu> <%lu> <%llu>'\n", a, ushort_a, uchar_a, ulong_a, ullong_a);
    // ft_printf("ft_printf: u, hu, hhu, lu, llu '<%u> <%hu> <%hhu> <%lu> <%llu>'\n", a, ushort_a, uchar_a, ulong_a, ullong_a);
	// printf("   printf: x, #x, hx, hhx, lx, llx '<%x> <%#x> <%hx> <%hhx> <%lx> <%llx>'\n", a, a, ushort_a, uchar_a, ulong_a, ullong_a);
    // ft_printf("ft_printf: x, #x, hx, hhx, lx, llx '<%x> <%#x> <%hx> <%hhx> <%lx> <%llx>'\n", a, a, ushort_a, uchar_a, ulong_a, ullong_a);
	// printf("   printf: double percent '<%%>'\n");
	// ft_printf("ft_printf: double percent '<%%>'\n");
	// ft_printf("%9999s\n", "crash");
    // ft_printf("test\n");

//		 printf("   printf: s '%s'\n", str);
//	 ft_printf("ft_printf: s '%s'\n", str);
//	 printf("   printf: 5s '%5s'\n", str);
//	 ft_printf("ft_printf: 5s '%5s'\n", str);
//	 printf("   printf: s0 '%.0s'\n", str);
//	 ft_printf("ft_printf: s0 '%.0s'\n", str);
//	 printf("   printf: s1 '%.1s'\n", str);
//	 ft_printf("ft_printf: s1 '%.1s'\n", str);
//	 printf("   printf: s2 '%.2s'\n", str);
//	 ft_printf("ft_printf: s2 '%.2s'\n", str);
//	 printf("   printf: s3 '%.3s'\n", str);
//	 ft_printf("ft_printf: s3 '%.3s'\n", str);
//	 printf("   printf: s7 '%.7s'\n", str);
//	 ft_printf("ft_printf: s7 '%.7s'\n", str);
//	 printf("   printf: s11 '%.11s'\n", str);
//	 ft_printf("ft_printf: s11 '%.11s'\n", str);
//	 printf("   printf: 5s11 '%5.11s'\n", str);
//	 ft_printf("ft_printf: 5s11 '%5.11s'\n", str);
//	 printf("   printf: 11s11 '%11.11s'\n", str);
//	 ft_printf("ft_printf: 11s11 '%11.11s'\n", str);
//	 printf("   printf: 12s11 '%12.11s'\n", str);
//	 ft_printf("ft_printf: 12s11 '%12.11s'\n", str);
//	 printf("   printf: 40s40 '%40.40s'\n", str);
//	 ft_printf("ft_printf: 40s40 '%40.40s'\n", str);
//	 printf("   printf: 50s48 '%50.48s'\n", str);
//	 ft_printf("ft_printf: 50s48 '%50.48s'\n", str);
//	 printf("   printf: s100 '%.100s'\n", str);
//	 ft_printf("ft_printf: s100 '%.100s'\n", str);

	//	 printf("   printf: p '%p'\n", &a);
//	 ft_printf("ft_printf: p '%p'\n", &a);
//	 printf("   printf: 18p '%18p'\n", &a);
//	 ft_printf("ft_printf: 18p '%18p'\n", &a);

//	 printf("   printf: c '%c'\n", c);
//	 ft_printf("ft_printf: c '%c'\n", c);
//	 printf("   printf: 5c '%5c'\n", c);
//	 ft_printf("ft_printf: 5c '%5c'\n", c);



//	 printf("   printf: d '%d'\n", a);
//	 ft_printf("ft_printf: d '%d'\n", a);
//	 printf("   printf: 9d '%9d'\n", a);
//	 ft_printf("ft_printf: 9d '%9d'\n", a);
//	 printf("   printf: -9d '%-9d'\n", a);
//	 ft_printf("ft_printf: -9d '%-9d'\n", a);
//	 printf("   printf: 09d '%09d'\n", a);
//	 ft_printf("ft_printf: 09d '%09d'\n", a);
//	 printf("   printf: spd '% d'\n", a);
//	 ft_printf("ft_printf: spd '% d'\n", a);
//	 printf("   printf: +d '%+d'\n", a);
//	 ft_printf("ft_printf: +d '%+d'\n", a);
//	 printf("   printf: +9d '%+9d'\n", a);
//	 ft_printf("ft_printf: +9d '%+9d'\n", a);
//	 printf("   printf: -+9d '%-+9d'\n", a);
//	 ft_printf("ft_printf: -+9d '%-+9d'\n", a);
//	  printf("   printf: hd '%hd'\n", short_a);
//	  ft_printf("ft_printf: hd '%hd'\n", short_a);
//	 printf("   printf: 9hd '%9hd'\n", short_a);
//	 ft_printf("ft_printf: 9hd '%9hd'\n", short_a);
//	 printf("   printf: -9hd '%-9hd'\n", short_a);
//	 ft_printf("ft_printf: -9hd '%-9hd'\n", short_a);
//	 printf("   printf: 09hd '%09hd'\n", short_a);
//	 ft_printf("ft_printf: 09hd '%09hd'\n", short_a);
//	 printf("   printf: +hd '%+hd'\n", short_a);
//	 ft_printf("ft_printf: +hd '%+hd'\n", short_a);
//	 printf("   printf: +9hd '%+9hd'\n", short_a);
//	 ft_printf("ft_printf: +9hd '%+9hd'\n", short_a);
//	 printf("   printf: -+9hd '%-+9hd'\n", short_a);
//	 ft_printf("ft_printf: -+9hd '%-+9hd'\n", short_a);
//	 printf("   printf: +09hd '%+09hd'\n", short_a);
//	 ft_printf("ft_printf: +09hd '%+09hd'\n", short_a);
//	  printf("   printf: hhd '%hhd'\n", signchar_a);
//	  ft_printf("ft_printf: hhd '%hhd'\n", signchar_a);
//	 printf("   printf: 9hhd '%9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: 9hhd '%9hhd'\n", signchar_a);
//	 printf("   printf: -9hhd '%-9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: -9hhd '%-9hhd'\n", signchar_a);
//	 printf("   printf: 09hhd '%09hhd'\n", signchar_a);
//	 ft_printf("ft_printf: 09hhd '%09hhd'\n", signchar_a);
//	 printf("   printf: +hhd '%+hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +hhd '%+hhd'\n", signchar_a);
//	 printf("   printf: +9hhd '%+9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +9hhd '%+9hhd'\n", signchar_a);
//	 printf("   printf: -+9hhd '%-+9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: -+9hhd '%-+9hhd'\n", signchar_a);
//	 printf("   printf: +09hhd '%+09hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +09hhd '%+09hhd'\n", signchar_a);
	 // printf("   printf: ld '%ld'\n", long_a);
	 // ft_printf("ft_printf: ld '%ld'\n", long_a);
//	 printf("   printf: 9ld '%9ld'\n", long_a);
//	 ft_printf("ft_printf: 9ld '%9ld'\n", long_a);
//	 printf("   printf: -9ld '%-9ld'\n", long_a);
//	 ft_printf("ft_printf: -9ld '%-9ld'\n", long_a);
//	 printf("   printf: 09ld '%09ld'\n", long_a);
//	 ft_printf("ft_printf: 09ld '%09ld'\n", long_a);
//	 printf("   printf: +ld '%+ld'\n", long_a);
//	 ft_printf("ft_printf: +ld '%+ld'\n", long_a);
//	 printf("   printf: +9ld '%+9ld'\n", long_a);
//	 ft_printf("ft_printf: +9ld '%+9ld'\n", long_a);
//	 printf("   printf: -+9ld '%-+9ld'\n", long_a);
//	 ft_printf("ft_printf: -+9ld '%-+9ld'\n", long_a);
//	 printf("   printf: +09ld '%+09ld'\n", long_a);
//	 ft_printf("ft_printf: +09ld '%+09ld'\n", long_a);
	 // printf("   printf: lld '%lld'\n", llong_a);
	 // ft_printf("ft_printf: lld '%lld'\n", llong_a);
//	 printf("   printf: 9lld '%9lld'\n", llong_a);
//	 ft_printf("ft_printf: 9lld '%9lld'\n", llong_a);
//	 printf("   printf: -9lld '%-9lld'\n", llong_a);
//	 ft_printf("ft_printf: -9lld '%-9lld'\n", llong_a);
//	 printf("   printf: 09lld '%09lld'\n", llong_a);
//	 ft_printf("ft_printf: 09lld '%09lld'\n", llong_a);
//	 printf("   printf: +lld '%+lld'\n", llong_a);
//	 ft_printf("ft_printf: +lld '%+lld'\n", llong_a);
//	 printf("   printf: +9lld '%+9lld'\n", llong_a);
//	 ft_printf("ft_printf: +9lld '%+9lld'\n", llong_a);
//	 printf("   printf: -+9lld '%-+9lld'\n", llong_a);
//	 ft_printf("ft_printf: -+9lld '%-+9lld'\n", llong_a);
//	 printf("   printf: +09lld '%+09lld'\n", llong_a);
//	 ft_printf("ft_printf: +09lld '%+09lld'\n", llong_a);
//	 printf("   printf: d0 '%.0d'\n", a);
//	 ft_printf("ft_printf: d0 '%.0d'\n", a);
//	 printf("   printf: d2 '%.2d'\n", a);
//	 ft_printf("ft_printf: d2 '%.2d'\n", a);
//	 printf("   printf: d5 '%.5d'\n", a);
//	 ft_printf("ft_printf: d5 '%.5d'\n", a);
//	 printf("   printf: d9 '%.9d'\n", a);
//	 ft_printf("ft_printf: d9 '%.9d'\n", a);
//	 printf("   printf: +d9 '%+.9d'\n", a);
//	 ft_printf("ft_printf: +d9 '%+.9d'\n", a);
//	 printf("   printf: 4d9 '%4.9d'\n", a);
//	 ft_printf("ft_printf: 4d9 '%4.9d'\n", a);
//	 printf("   printf: -4d9 '%-4.9d'\n", a);
//	 ft_printf("ft_printf: -4d9 '%-4.9d'\n", a);
//	 printf("   printf: 9d9 '%9.9d'\n", a);
//	 ft_printf("ft_printf: 9d9 '%9.9d'\n", a);
//	 printf("   printf: -9d9 '%-9.9d'\n", a);
//	 ft_printf("ft_printf: -9d9 '%-9.9d'\n", a);
//	 printf("   printf: 20d9 '%20.9d'\n", a);
//	 ft_printf("ft_printf: 20d9 '%20.9d'\n", a);
	 // printf("   printf: -20d9 '%-20.9d'\n", a);
	 // ft_printf("ft_printf: -20d9 '%-20.9d'\n", a);
//	 printf("   printf: hd9 '%.9hd'\n", short_a);
//	 ft_printf("ft_printf: hd9 '%.9hd'\n", short_a);
//	 printf("   printf: 4hd9 '%4.9hd'\n", short_a);
//	 ft_printf("ft_printf: 4hd9 '%4.9hd'\n", short_a);
//	 printf("   printf: -4hd9 '%-4.9hd'\n", short_a);
//	 ft_printf("ft_printf: -4hd9 '%-4.9hd'\n", short_a);
//	 printf("   printf: 9hd9 '%9.9hd'\n", short_a);
//	 ft_printf("ft_printf: 9hd9 '%9.9hd'\n", short_a);
//	 printf("   printf: -9hd9 '%-9.9hd'\n", short_a);
//	 ft_printf("ft_printf: -9hd9 '%-9.9hd'\n", short_a);
//	 printf("   printf: 20hd9 '%20.9hd'\n", short_a);
//	 ft_printf("ft_printf: 20hd9 '%20.9hd'\n", short_a);
//	 printf("   printf: -20hd9 '%-20.9hd'\n", short_a);
//	 ft_printf("ft_printf: -20hd9 '%-20.9hd'\n", short_a);
//	 printf("   printf: +4hd9 '%+4.9hd'\n", short_a);
//	 ft_printf("ft_printf: +4hd9 '%+4.9hd'\n", short_a);
//	 printf("   printf: -+4hd9 '%-+4.9hd'\n", short_a);
//	 ft_printf("ft_printf: -+4hd9 '%-+4.9hd'\n", short_a);
//	 printf("   printf: +9hd9 '%+9.9hd'\n", short_a);
//	 ft_printf("ft_printf: +9hd9 '%+9.9hd'\n", short_a);
//	 printf("   printf: -+9hd9 '%-+9.9hd'\n", short_a);
//	 ft_printf("ft_printf: -+9hd9 '%-+9.9hd'\n", short_a);
//	 printf("   printf: +20hd9 '%+20.9hd'\n", short_a);
//	 ft_printf("ft_printf: +20hd9 '%+20.9hd'\n", short_a);
//	 printf("   printf: -+20hd9 '%-+20.9hd'\n", short_a);
//	 ft_printf("ft_printf: -+20hd9 '%-+20.9hd'\n", short_a);
//	 printf("   printf: +04hd9 '%+04.9hd'\n", short_a);
//	 ft_printf("ft_printf: +04hd9 '%+04.9hd'\n", short_a);
//	 printf("   printf: +09hd9 '%+09.9hd'\n", short_a);
//	 ft_printf("ft_printf: +09hd9 '%+09.9hd'\n", short_a);
//	 printf("   printf: +020hd9 '%+020.9hd'\n", short_a);
//	 ft_printf("ft_printf: +020hd9 '%+020.9hd'\n", short_a);
//	 printf("   printf: hhd9 '%.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: hhd9 '%.9hhd'\n", signchar_a);
//	 printf("   printf: 4hhd9 '%4.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: 4hhd9 '%4.9hhd'\n", signchar_a);
//	 printf("   printf: -4hhd9 '%-4.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: -4hhd9 '%-4.9hhd'\n", signchar_a);
//	 printf("   printf: 9hhd9 '%9.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: 9hhd9 '%9.9hhd'\n", signchar_a);
//	 printf("   printf: -9hhd9 '%-9.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: -9hhd9 '%-9.9hhd'\n", signchar_a);
//	 printf("   printf: 20hhd9 '%20.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: 20hhd9 '%20.9hhd'\n", signchar_a);
//	 printf("   printf: -20hhd9 '%-20.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: -20hhd9 '%-20.9hhd'\n", signchar_a);
//	 printf("   printf: +4hhd9 '%+4.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +4hhd9 '%+4.9hhd'\n", signchar_a);
//	 printf("   printf: -+4hhd9 '%-+4.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: -+4hhd9 '%-+4.9hhd'\n", signchar_a);
//	 printf("   printf: +9hhd9 '%+9.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +9hhd9 '%+9.9hhd'\n", signchar_a);
//	 printf("   printf: -+9hhd9 '%-+9.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: -+9hhd9 '%-+9.9hhd'\n", signchar_a);
//	 printf("   printf: +20hhd9 '%+20.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +20hhd9 '%+20.9hhd'\n", signchar_a);
//	 printf("   printf: -+20hhd9 '%-+20.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: -+20hhd9 '%-+20.9hhd'\n", signchar_a);
//	 printf("   printf: +04hhd9 '%+04.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +04hhd9 '%+04.9hhd'\n", signchar_a);
//	 printf("   printf: +09hhd9 '%+09.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +09hhd9 '%+09.9hhd'\n", signchar_a);
//	 printf("   printf: +020hhd9 '%+020.9hhd'\n", signchar_a);
//	 ft_printf("ft_printf: +020hhd9 '%+020.9hhd'\n", signchar_a);
//	 printf("   printf: ld9 '%.9ld'\n", long_a);
//	 ft_printf("ft_printf: ld9 '%.9ld'\n", long_a);
//	 printf("   printf: 4ld9 '%4.9ld'\n", long_a);
//	 ft_printf("ft_printf: 4ld9 '%4.9ld'\n", long_a);
//	 printf("   printf: -4ld9 '%-4.9ld'\n", long_a);
//	 ft_printf("ft_printf: -4ld9 '%-4.9ld'\n", long_a);
//	 printf("   printf: 9ld9 '%9.9ld'\n", long_a);
//	 ft_printf("ft_printf: 9ld9 '%9.9ld'\n", long_a);
//	 printf("   printf: -9ld9 '%-9.9ld'\n", long_a);
//	 ft_printf("ft_printf: -9ld9 '%-9.9ld'\n", long_a);
//	 printf("   printf: 20ld9 '%20.9ld'\n", long_a);
//	 ft_printf("ft_printf: 20ld9 '%20.9ld'\n", long_a);
//	 printf("   printf: -20ld9 '%-20.9ld'\n", long_a);
//	 ft_printf("ft_printf: -20ld9 '%-20.9ld'\n", long_a);
//	 printf("   printf: 04ld9 '%04.9ld'\n", long_a);
//	 ft_printf("ft_printf: 04ld9 '%04.9ld'\n", long_a);
//	 printf("   printf: 09ld9 '%09.9ld'\n", long_a);
//	 ft_printf("ft_printf: 09ld9 '%09.9ld'\n", long_a);
//	 printf("   printf: 020ld9 '%020.9ld'\n", long_a);
//	 ft_printf("ft_printf: 020ld9 '%020.9ld'\n", long_a);
//	 printf("   printf: +ld9 '%+.9ld'\n", long_a);
//	 ft_printf("ft_printf: +ld9 '%+.9ld'\n", long_a);
//	 printf("   printf: +4ld9 '%+4.9ld'\n", long_a);
//	 ft_printf("ft_printf: +4ld9 '%+4.9ld'\n", long_a);
//	 printf("   printf: -+4ld9 '%-+4.9ld'\n", long_a);
//	 ft_printf("ft_printf: -+4ld9 '%-+4.9ld'\n", long_a);
//	 printf("   printf: +9ld9 '%+9.9ld'\n", long_a);
//	 ft_printf("ft_printf: +9ld9 '%+9.9ld'\n", long_a);
//	 printf("   printf: -+9ld9 '%-+9.9ld'\n", long_a);
//	 ft_printf("ft_printf: +9ld9 '%-+9.9ld'\n", long_a);
//	 printf("   printf: +20ld9 '%+20.9ld'\n", long_a);
//	 ft_printf("ft_printf: +20ld9 '%+20.9ld'\n", long_a);
//	 printf("   printf: -+20ld9 '%-+20.9ld'\n", long_a);
//	 ft_printf("ft_printf: -+20ld9 '%-+20.9ld'\n", long_a);
//	 printf("   printf: +04ld9 '%+04.9ld'\n", long_a);
//	 ft_printf("ft_printf: +04ld9 '%+04.9ld'\n", long_a);
//	 printf("   printf: +09ld9 '%+09.9ld'\n", long_a);
//	 ft_printf("ft_printf: +09ld9 '%+09.9ld'\n", long_a);
//	 printf("   printf: +020ld9 '%+020.9ld'\n", long_a);
//	 ft_printf("ft_printf: +020ld9 '%+020.9ld'\n", long_a);
//	 printf("   printf: lld9 '%.9lld'\n", llong_a);
//	 ft_printf("ft_printf: lld9 '%.9lld'\n", llong_a);
//	 printf("   printf: 4lld9 '%4.9lld'\n", llong_a);
//	 ft_printf("ft_printf: 4lld9 '%4.9lld'\n", llong_a);
//	 printf("   printf: -4lld9 '%-4.9lld'\n", llong_a);
//	 ft_printf("ft_printf: -4lld9 '%-4.9lld'\n", llong_a);
//	 printf("   printf: 9lld9 '%9.9lld'\n", llong_a);
//	 ft_printf("ft_printf: 9lld9 '%9.9lld'\n", llong_a);
//	 printf("   printf: -9lld9 '%-9.9lld'\n", llong_a);
//	 ft_printf("ft_printf: -9lld9 '%-9.9lld'\n", llong_a);
//	 printf("   printf: 20lld9 '%20.9lld'\n", llong_a);
//	 ft_printf("ft_printf: 20lld9 '%20.9lld'\n", llong_a);
//	 printf("   printf: -20lld9 '%-20.9lld'\n", llong_a);
//	 ft_printf("ft_printf: -20lld9 '%-20.9lld'\n", llong_a);
//	 printf("   printf: 04lld9 '%04.9lld'\n", llong_a);
//	 ft_printf("ft_printf: 04lld9 '%04.9lld'\n", llong_a);
//	 printf("   printf: 09lld9 '%09.9lld'\n", llong_a);
//	 ft_printf("ft_printf: 09lld9 '%09.9lld'\n", llong_a);
//	 printf("   printf: 020lld9 '%020.9lld'\n", llong_a);
//	 ft_printf("ft_printf: 020lld9 '%020.9lld'\n", llong_a);
//	 printf("   printf: +4lld9 '%+4.9lld'\n", llong_a);
//	 ft_printf("ft_printf: +4lld9 '%+4.9lld'\n", llong_a);
//	 printf("   printf: -+4lld9 '%-+4.9lld'\n", llong_a);
//	 ft_printf("ft_printf: -+4lld9 '%-+4.9lld'\n", llong_a);
//	 printf("   printf: +9lld9 '%+9.9lld'\n", llong_a);
//	 ft_printf("ft_printf: +9lld9 '%+9.9lld'\n", llong_a);
//	 printf("   printf: -+9lld9 '%-+9.9lld'\n", llong_a);
//	 ft_printf("ft_printf: -+9lld9 '%-+9.9lld'\n", llong_a);
//	 printf("   printf: +20lld9 '%+20.9lld'\n", llong_a);
//	 ft_printf("ft_printf: +20lld9 '%+20.9lld'\n", llong_a);
//	 printf("   printf: -+20lld9 '%-+20.9lld'\n", llong_a);
//	 ft_printf("ft_printf: -+20lld9 '%-+20.9lld'\n", llong_a);
//	 printf("   printf: +04lld9 '%+04.9lld'\n", llong_a);
//	 ft_printf("ft_printf: +04lld9 '%+04.9lld'\n", llong_a);
//	 printf("   printf: +09lld9 '%+09.9lld'\n", llong_a);
//	 ft_printf("ft_printf: +09lld9 '%+09.9lld'\n", llong_a);
//	 printf("   printf: +020lld9 '%+020.9lld'\n", llong_a);
//	 ft_printf("ft_printf: +020lld9 '%+020.9lld'\n", llong_a);
//
//
//	 printf("   printf: i '%i'\n", a);
//	 ft_printf("ft_printf: i '%i'\n", a);
//	 printf("   printf: 9i '%9i'\n", a);
//	 ft_printf("ft_printf: 9i '%9i'\n", a);
//	 printf("   printf: -9i '%-9i'\n", a);
//	 ft_printf("ft_printf: -9i '%-9i'\n", a);
//	 printf("   printf: 09i '%09i'\n", a);
//	 ft_printf("ft_printf: 09i '%09i'\n", a);
//	 printf("   printf: spi '% i'\n", a);
//	 ft_printf("ft_printf: spi '% i'\n", a);
//	 printf("   printf: +i '%+i'\n", a);
//	 ft_printf("ft_printf: +i '%+i'\n", a);
//	 printf("   printf: +9i '%+9i'\n", a);
//	 ft_printf("ft_printf: +9i '%+9i'\n", a);
//	 printf("   printf: -+9i '%-+9i'\n", a);
//	 ft_printf("ft_printf: -+9i '%-+9i'\n", a);
//	 printf("   printf: hi '%hi'\n", short_a);
//	 ft_printf("ft_printf: hi '%hi'\n", short_a);
//	 printf("   printf: 9hi '%9hi'\n", short_a);
//	 ft_printf("ft_printf: 9hi '%9hi'\n", short_a);
//	 printf("   printf: -9hi '%-9hi'\n", short_a);
//	 ft_printf("ft_printf: -9hi '%-9hi'\n", short_a);
//	 printf("   printf: 09hi '%09hi'\n", short_a);
//	 ft_printf("ft_printf: 09hi '%09hi'\n", short_a);
//	 printf("   printf: +hi '%+hi'\n", short_a);
//	 ft_printf("ft_printf: +hi '%+hi'\n", short_a);
//	 printf("   printf: +9hi '%+9hi'\n", short_a);
//	 ft_printf("ft_printf: +9hi '%+9hi'\n", short_a);
//	 printf("   printf: -+9hi '%-+9hi'\n", short_a);
//	 ft_printf("ft_printf: -+9hi '%-+9hi'\n", short_a);
//	 printf("   printf: +09hi '%+09hi'\n", short_a);
//	 ft_printf("ft_printf: +09hi '%+09hi'\n", short_a);
//	 printf("   printf: hhi '%hhi'\n", signchar_a);
//	 ft_printf("ft_printf: hhi '%hhi'\n", signchar_a);
//	 printf("   printf: 9hhi '%9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: 9hhi '%9hhi'\n", signchar_a);
//	 printf("   printf: -9hhi '%-9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: -9hhi '%-9hhi'\n", signchar_a);
//	 printf("   printf: 09hhi '%09hhi'\n", signchar_a);
//	 ft_printf("ft_printf: 09hhi '%09hhi'\n", signchar_a);
//	 printf("   printf: +hhi '%+hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +hhi '%+hhi'\n", signchar_a);
//	 printf("   printf: +9hhi '%+9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +9hhi '%+9hhi'\n", signchar_a);
//	 printf("   printf: -+9hhi '%-+9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: -+9hhi '%-+9hhi'\n", signchar_a);
//	 printf("   printf: +09hhi '%+09hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +09hhi '%+09hhi'\n", signchar_a);
//	 printf("   printf: li '%li'\n", long_a);
//	 ft_printf("ft_printf: li '%li'\n", long_a);
//	 printf("   printf: 9li '%9li'\n", long_a);
//	 ft_printf("ft_printf: 9li '%9li'\n", long_a);
//	 printf("   printf: -9li '%-9li'\n", long_a);
//	 ft_printf("ft_printf: -9li '%-9li'\n", long_a);
//	 printf("   printf: 09li '%09li'\n", long_a);
//	 ft_printf("ft_printf: 09li '%09li'\n", long_a);
//	 printf("   printf: +li '%+li'\n", long_a);
//	 ft_printf("ft_printf: +li '%+li'\n", long_a);
//	 printf("   printf: +9li '%+9li'\n", long_a);
//	 ft_printf("ft_printf: +9li '%+9li'\n", long_a);
//	 printf("   printf: -+9li '%-+9li'\n", long_a);
//	 ft_printf("ft_printf: -+9li '%-+9li'\n", long_a);
//	 printf("   printf: +09li '%+09li'\n", long_a);
//	 ft_printf("ft_printf: +09li '%+09li'\n", long_a);
//	 printf("   printf: lli '%lli'\n", llong_a);
//	 ft_printf("ft_printf: lli '%lli'\n", llong_a);
//	 printf("   printf: 9lli '%9lli'\n", llong_a);
//	 ft_printf("ft_printf: 9lli '%9lli'\n", llong_a);
//	 printf("   printf: -9lli '%-9lli'\n", llong_a);
//	 ft_printf("ft_printf: -9lli '%-9lli'\n", llong_a);
//	 printf("   printf: 09lli '%09lli'\n", llong_a);
//	 ft_printf("ft_printf: 09lli '%09lli'\n", llong_a);
//	 printf("   printf: +lli '%+lli'\n", llong_a);
//	 ft_printf("ft_printf: +lli '%+lli'\n", llong_a);
//	 printf("   printf: +9lli '%+9lli'\n", llong_a);
//	 ft_printf("ft_printf: +9lli '%+9lli'\n", llong_a);
//	 printf("   printf: -+9lli '%-+9lli'\n", llong_a);
//	 ft_printf("ft_printf: -+9lli '%-+9lli'\n", llong_a);
//	 printf("   printf: +09lli '%+09lli'\n", llong_a);
//	 ft_printf("ft_printf: +09lli '%+09lli'\n", llong_a);
//	 printf("   printf: i0 '%.0i'\n", a);
//	 ft_printf("ft_printf: i0 '%.0i'\n", a);
//	 printf("   printf: i2 '%.2i'\n", a);
//	 ft_printf("ft_printf: i2 '%.2i'\n", a);
//	 printf("   printf: i5 '%.5i'\n", a);
//	 ft_printf("ft_printf: i5 '%.5i'\n", a);
//	 printf("   printf: i9 '%.9i'\n", a);
//	 ft_printf("ft_printf: i9 '%.9i'\n", a);
//	 printf("   printf: +i9 '%+.9i'\n", a);
//	 ft_printf("ft_printf: +i9 '%+.9i'\n", a);
//	 printf("   printf: 4i9 '%4.9i'\n", a);
//	 ft_printf("ft_printf: 4i9 '%4.9i'\n", a);
//	 printf("   printf: -4i9 '%-4.9i'\n", a);
//	 ft_printf("ft_printf: -4i9 '%-4.9i'\n", a);
//	 printf("   printf: 9i9 '%9.9i'\n", a);
//	 ft_printf("ft_printf: 9i9 '%9.9i'\n", a);
//	 printf("   printf: -9i9 '%-9.9i'\n", a);
//	 ft_printf("ft_printf: -9i9 '%-9.9i'\n", a);
//	 printf("   printf: 20i9 '%20.9i'\n", a);
//	 ft_printf("ft_printf: 20i9 '%20.9i'\n", a);
//	 printf("   printf: -20i9 '%-20.9i'\n", a);
//	 ft_printf("ft_printf: -20i9 '%-20.9i'\n", a);
//	 printf("   printf: hi9 '%.9hi'\n", short_a);
//	 ft_printf("ft_printf: hi9 '%.9hi'\n", short_a);
//	 printf("   printf: 4hi9 '%4.9hi'\n", short_a);
//	 ft_printf("ft_printf: 4hi9 '%4.9hi'\n", short_a);
//	 printf("   printf: -4hi9 '%-4.9hi'\n", short_a);
//	 ft_printf("ft_printf: -4hi9 '%-4.9hi'\n", short_a);
//	 printf("   printf: 9hi9 '%9.9hi'\n", short_a);
//	 ft_printf("ft_printf: 9hi9 '%9.9hi'\n", short_a);
//	 printf("   printf: -9hi9 '%-9.9hi'\n", short_a);
//	 ft_printf("ft_printf: -9hi9 '%-9.9hi'\n", short_a);
//	 printf("   printf: 20hi9 '%20.9hi'\n", short_a);
//	 ft_printf("ft_printf: 20hi9 '%20.9hi'\n", short_a);
//	 printf("   printf: -20hi9 '%-20.9hi'\n", short_a);
//	 ft_printf("ft_printf: -20hi9 '%-20.9hi'\n", short_a);
//	 printf("   printf: +4hi9 '%+4.9hi'\n", short_a);
//	 ft_printf("ft_printf: +4hi9 '%+4.9hi'\n", short_a);
//	 printf("   printf: -+4hi9 '%-+4.9hi'\n", short_a);
//	 ft_printf("ft_printf: -+4hi9 '%-+4.9hi'\n", short_a);
//	 printf("   printf: +9hi9 '%+9.9hi'\n", short_a);
//	 ft_printf("ft_printf: +9hi9 '%+9.9hi'\n", short_a);
//	 printf("   printf: -+9hi9 '%-+9.9hi'\n", short_a);
//	 ft_printf("ft_printf: -+9hi9 '%-+9.9hi'\n", short_a);
//	 printf("   printf: +20hi9 '%+20.9hi'\n", short_a);
//	 ft_printf("ft_printf: +20hi9 '%+20.9hi'\n", short_a);
//	 printf("   printf: -+20hi9 '%-+20.9hi'\n", short_a);
//	 ft_printf("ft_printf: -+20hi9 '%-+20.9hi'\n", short_a);
//	 printf("   printf: +04hi9 '%+04.9hi'\n", short_a);
//	 ft_printf("ft_printf: +04hi9 '%+04.9hi'\n", short_a);
//	 printf("   printf: +09hi9 '%+09.9hi'\n", short_a);
//	 ft_printf("ft_printf: +09hi9 '%+09.9hi'\n", short_a);
//	 printf("   printf: +020hi9 '%+020.9hi'\n", short_a);
//	 ft_printf("ft_printf: +020hi9 '%+020.9hi'\n", short_a);
//	 printf("   printf: hhi9 '%.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: hhi9 '%.9hhi'\n", signchar_a);
//	 printf("   printf: 4hhi9 '%4.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: 4hhi9 '%4.9hhi'\n", signchar_a);
//	 printf("   printf: -4hhi9 '%-4.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: -4hhi9 '%-4.9hhi'\n", signchar_a);
//	 printf("   printf: 9hhi9 '%9.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: 9hhi9 '%9.9hhi'\n", signchar_a);
//	 printf("   printf: -9hhi9 '%-9.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: -9hhi9 '%-9.9hhi'\n", signchar_a);
//	 printf("   printf: 20hhi9 '%20.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: 20hhi9 '%20.9hhi'\n", signchar_a);
//	 printf("   printf: -20hhi9 '%-20.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: -20hhi9 '%-20.9hhi'\n", signchar_a);
//	 printf("   printf: +4hhi9 '%+4.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +4hhi9 '%+4.9hhi'\n", signchar_a);
//	 printf("   printf: -+4hhi9 '%-+4.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: -+4hhi9 '%-+4.9hhi'\n", signchar_a);
//	 printf("   printf: +9hhi9 '%+9.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +9hhi9 '%+9.9hhi'\n", signchar_a);
//	 printf("   printf: -+9hhi9 '%-+9.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: -+9hhi9 '%-+9.9hhi'\n", signchar_a);
//	 printf("   printf: +20hhi9 '%+20.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +20hhi9 '%+20.9hhi'\n", signchar_a);
//	 printf("   printf: -+20hhi9 '%-+20.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: -+20hhi9 '%-+20.9hhi'\n", signchar_a);
//	 printf("   printf: +04hhi9 '%+04.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +04hhi9 '%+04.9hhi'\n", signchar_a);
//	 printf("   printf: +09hhi9 '%+09.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +09hhi9 '%+09.9hhi'\n", signchar_a);
//	 printf("   printf: +020hhi9 '%+020.9hhi'\n", signchar_a);
//	 ft_printf("ft_printf: +020hhi9 '%+020.9hhi'\n", signchar_a);
//	 printf("   printf: li9 '%.9li'\n", long_a);
//	 ft_printf("ft_printf: li9 '%.9li'\n", long_a);
//	 printf("   printf: 4li9 '%4.9li'\n", long_a);
//	 ft_printf("ft_printf: 4li9 '%4.9li'\n", long_a);
//	 printf("   printf: -4li9 '%-4.9li'\n", long_a);
//	 ft_printf("ft_printf: -4li9 '%-4.9li'\n", long_a);
//	 printf("   printf: 9li9 '%9.9li'\n", long_a);
//	 ft_printf("ft_printf: 9li9 '%9.9li'\n", long_a);
//	 printf("   printf: -9li9 '%-9.9li'\n", long_a);
//	 ft_printf("ft_printf: -9li9 '%-9.9li'\n", long_a);
//	 printf("   printf: 20li9 '%20.9li'\n", long_a);
//	 ft_printf("ft_printf: 20li9 '%20.9li'\n", long_a);
//	 printf("   printf: -20li9 '%-20.9li'\n", long_a);
//	 ft_printf("ft_printf: -20li9 '%-20.9li'\n", long_a);
//	 printf("   printf: 04li9 '%04.9li'\n", long_a);
//	 ft_printf("ft_printf: 04li9 '%04.9li'\n", long_a);
//	 printf("   printf: 09li9 '%09.9li'\n", long_a);
//	 ft_printf("ft_printf: 09li9 '%09.9li'\n", long_a);
//	 printf("   printf: 020li9 '%020.9li'\n", long_a);
//	 ft_printf("ft_printf: 020li9 '%020.9li'\n", long_a);
//	 printf("   printf: +li9 '%+.9li'\n", long_a);
//	 ft_printf("ft_printf: +li9 '%+.9li'\n", long_a);
//	 printf("   printf: +4li9 '%+4.9li'\n", long_a);
//	 ft_printf("ft_printf: +4li9 '%+4.9li'\n", long_a);
//	 printf("   printf: -+4li9 '%-+4.9li'\n", long_a);
//	 ft_printf("ft_printf: -+4li9 '%-+4.9li'\n", long_a);
//	 printf("   printf: +9li9 '%+9.9li'\n", long_a);
//	 ft_printf("ft_printf: +9li9 '%+9.9li'\n", long_a);
//	 printf("   printf: -+9li9 '%-+9.9li'\n", long_a);
//	 ft_printf("ft_printf: +9li9 '%-+9.9li'\n", long_a);
//	 printf("   printf: +20li9 '%+20.9li'\n", long_a);
//	 ft_printf("ft_printf: +20li9 '%+20.9li'\n", long_a);
//	 printf("   printf: -+20li9 '%-+20.9li'\n", long_a);
//	 ft_printf("ft_printf: -+20li9 '%-+20.9li'\n", long_a);
//	 printf("   printf: +04li9 '%+04.9li'\n", long_a);
//	 ft_printf("ft_printf: +04li9 '%+04.9li'\n", long_a);
//	 printf("   printf: +09li9 '%+09.9li'\n", long_a);
//	 ft_printf("ft_printf: +09li9 '%+09.9li'\n", long_a);
//	 printf("   printf: +020li9 '%+020.9li'\n", long_a);
//	 ft_printf("ft_printf: +020li9 '%+020.9li'\n", long_a);
//	 printf("   printf: lli9 '%.9lli'\n", llong_a);
//	 ft_printf("ft_printf: lli9 '%.9lli'\n", llong_a);
//	 printf("   printf: 4lli9 '%4.9lli'\n", llong_a);
//	 ft_printf("ft_printf: 4lli9 '%4.9lli'\n", llong_a);
//	 printf("   printf: -4lli9 '%-4.9lli'\n", llong_a);
//	 ft_printf("ft_printf: -4lli9 '%-4.9lli'\n", llong_a);
//	 printf("   printf: 9lli9 '%9.9lli'\n", llong_a);
//	 ft_printf("ft_printf: 9lli9 '%9.9lli'\n", llong_a);
//	 printf("   printf: -9lli9 '%-9.9lli'\n", llong_a);
//	 ft_printf("ft_printf: -9lli9 '%-9.9lli'\n", llong_a);
//	 printf("   printf: 20lli9 '%20.9lli'\n", llong_a);
//	 ft_printf("ft_printf: 20lli9 '%20.9lli'\n", llong_a);
//	 printf("   printf: -20lli9 '%-20.9lli'\n", llong_a);
//	 ft_printf("ft_printf: -20lli9 '%-20.9lli'\n", llong_a);
//	 printf("   printf: 04lli9 '%04.9lli'\n", llong_a);
//	 ft_printf("ft_printf: 04lli9 '%04.9lli'\n", llong_a);
//	 printf("   printf: 09lli9 '%09.9lli'\n", llong_a);
//	 ft_printf("ft_printf: 09lli9 '%09.9lli'\n", llong_a);
//	 printf("   printf: 020lli9 '%020.9lli'\n", llong_a);
//	 ft_printf("ft_printf: 020lli9 '%020.9lli'\n", llong_a);
//	 printf("   printf: +4lli9 '%+4.9lli'\n", llong_a);
//	 ft_printf("ft_printf: +4lli9 '%+4.9lli'\n", llong_a);
//	 printf("   printf: -+4lli9 '%-+4.9lli'\n", llong_a);
//	 ft_printf("ft_printf: -+4lli9 '%-+4.9lli'\n", llong_a);
//	 printf("   printf: +9lli9 '%+9.9lli'\n", llong_a);
//	 ft_printf("ft_printf: +9lli9 '%+9.9lli'\n", llong_a);
//	 printf("   printf: -+9lli9 '%-+9.9lli'\n", llong_a);
//	 ft_printf("ft_printf: -+9lli9 '%-+9.9lli'\n", llong_a);
//	 printf("   printf: +20lli9 '%+20.9lli'\n", llong_a);
//	 ft_printf("ft_printf: +20lli9 '%+20.9lli'\n", llong_a);
//	 printf("   printf: -+20lli9 '%-+20.9lli'\n", llong_a);
//	 ft_printf("ft_printf: -+20lli9 '%-+20.9lli'\n", llong_a);
//	 printf("   printf: +04lli9 '%+04.9lli'\n", llong_a);
//	 ft_printf("ft_printf: +04lli9 '%+04.9lli'\n", llong_a);
//	 printf("   printf: +09lli9 '%+09.9lli'\n", llong_a);
//	 ft_printf("ft_printf: +09lli9 '%+09.9lli'\n", llong_a);
//	 printf("   printf: +020lli9 '%+020.9lli'\n", llong_a);
//	 ft_printf("ft_printf: +020lli9 '%+020.9lli'\n", llong_a);
//
//	 printf("   printf: o '%o'\n", a);
//     ft_printf("ft_printf: o '%o'\n", a);
//	 printf("   printf: 8o '%8o'\n", a);
//	 ft_printf("ft_printf: 8o '%8o'\n", a);
//	 printf("   printf: -8o '%-8o'\n", a);
//	 ft_printf("ft_printf: -8o '%-8o'\n", a);
//	 printf("   printf: 08o '%08o'\n", a);
//	 ft_printf("ft_printf: 08o '%08o'\n", a);
//	 printf("   printf: #o '%#o'\n", a);
//	 ft_printf("ft_printf: #o '%#o'\n", a);
//	 printf("   printf: #8o '%#8o'\n", a);
//	 ft_printf("ft_printf: #8o '%#8o'\n", a);
//	 printf("   printf: #-8o '%#-8o'\n", a);
//	 ft_printf("ft_printf: #-8o '%#-8o'\n", a);
//	 printf("   printf: #08o '%#08o'\n", a);
//	 ft_printf("ft_printf: #08o '%#08o'\n", a);
//	 printf("   printf: ho '%ho'\n", ushort_a);
//	 ft_printf("ft_printf: ho '%ho'\n", ushort_a);
//	 printf("   printf: 8ho '%8ho'\n", ushort_a);
//	 ft_printf("ft_printf: 8ho '%8ho'\n", ushort_a);
//	 printf("   printf: -8ho '%-8ho'\n", ushort_a);
//	 ft_printf("ft_printf: -8ho '%-8ho'\n", ushort_a);
//	 printf("   printf: 08ho '%08ho'\n", ushort_a);
//	 ft_printf("ft_printf: 08ho '%08ho'\n", ushort_a);
//	 printf("   printf: #ho '%#ho'\n", ushort_a);
//	 ft_printf("ft_printf: #ho '%#ho'\n", ushort_a);
//	 printf("   printf: #8ho '%#8ho'\n", ushort_a);
//	 ft_printf("ft_printf: #8ho '%#8ho'\n", ushort_a);
//	 printf("   printf: #-8ho '%#-8ho'\n", ushort_a);
//	 ft_printf("ft_printf: #-8ho '%#-8ho'\n", ushort_a);
//	 printf("   printf: #08ho '%#08ho'\n", ushort_a);
//	 ft_printf("ft_printf: #08ho '%#08ho'\n", ushort_a);
//	 printf("   printf: hho '%hho'\n", uchar_a);
//	 ft_printf("ft_printf: hho '%hho'\n", uchar_a);
//	 printf("   printf: 8hho '%8hho'\n", uchar_a);
//	 ft_printf("ft_printf: 8hho '%8hho'\n", uchar_a);
//	 printf("   printf: -8hho '%-8hho'\n", uchar_a);
//	 ft_printf("ft_printf: -8hho '%-8hho'\n", uchar_a);
//	 printf("   printf: 08hho '%08hho'\n", uchar_a);
//	 ft_printf("ft_printf: 08hho '%08hho'\n", uchar_a);
//	 printf("   printf: #hho '%#hho'\n", uchar_a);
//	 ft_printf("ft_printf: #hho '%#hho'\n", uchar_a);
//	 printf("   printf: #8hho '%#8hho'\n", uchar_a);
//	 ft_printf("ft_printf: #8hho '%#8hho'\n", uchar_a);
//	 printf("   printf: #-8hho '%#-8hho'\n", uchar_a);
//	 ft_printf("ft_printf: #-8hho '%#-8hho'\n", uchar_a);
//	 printf("   printf: #08hho '%#08hho'\n", uchar_a);
//	 ft_printf("ft_printf: #08hho '%#08hho'\n", uchar_a);
//	 printf("   printf: lo '%lo'\n", ulong_a);
//	 ft_printf("ft_printf: lo '%lo'\n", ulong_a);
//	 printf("   printf: 25lo '%25lo'\n", ulong_a);
//	 ft_printf("ft_printf: 25lo '%25lo'\n", ulong_a);
//	 printf("   printf: -25lo '%-25lo'\n", ulong_a);
//	 ft_printf("ft_printf: -25lo '%-25lo'\n", ulong_a);
//	 printf("   printf: 025lo '%025lo'\n", ulong_a);
//	 ft_printf("ft_printf: 025lo '%025lo'\n", ulong_a);
//	 printf("   printf: #lo '%#lo'\n", ulong_a);
//	 ft_printf("ft_printf: #lo '%#lo'\n", ulong_a);
//	 printf("   printf: #25lo '%#25lo'\n", ulong_a);
//	 ft_printf("ft_printf: #25lo '%#25lo'\n", ulong_a);
//	 printf("   printf: #-25lo '%#-25lo'\n", ulong_a);
//	 ft_printf("ft_printf: #-25lo '%#-25lo'\n", ulong_a);
//	 printf("   printf: #025lo '%#025lo'\n", ulong_a);
//	 ft_printf("ft_printf: #025lo '%#025lo'\n", ulong_a);
//	 printf("   printf: llo '%llo'\n", ullong_a);
//	 ft_printf("ft_printf: llo '%llo'\n", ullong_a);
//	 printf("   printf: 25llo '%25llo'\n", ullong_a);
//	 ft_printf("ft_printf: 25llo '%25llo'\n", ullong_a);
//	 printf("   printf: -25llo '%-25llo'\n", ullong_a);
//	 ft_printf("ft_printf: -25llo '%-25llo'\n", ullong_a);
//	 printf("   printf: 025llo '%025llo'\n", ullong_a);
//	 ft_printf("ft_printf: 025llo '%025llo'\n", ullong_a);
//	 printf("   printf: #llo '%#llo'\n", ullong_a);
//	 ft_printf("ft_printf: #llo '%#llo'\n", ullong_a);
//	 printf("   printf: #25llo '%#25llo'\n", ullong_a);
//	 ft_printf("ft_printf: #25llo '%#25llo'\n", ullong_a);
//	 printf("   printf: #-25llo '%#-25llo'\n", ullong_a);
//	 ft_printf("ft_printf: #-25llo '%#-25llo'\n", ullong_a);
//	 printf("   printf: #025llo '%#025llo'\n", ullong_a);
//	 ft_printf("ft_printf: #025llo '%#025llo'\n", ullong_a);
//	 printf("   printf: o0 '%.0o'\n", a);
//	 ft_printf("ft_printf: o0 '%.0o'\n", a);
//	 printf("   printf: 0o0 '%0.0o'\n", a);
//	 ft_printf("ft_printf: 0o0 '%0.0o'\n", a);
//	 printf("   printf: #o0 '%#.0o'\n", a);
//	 ft_printf("ft_printf: #o0 '%#.0o'\n", a);
//	 printf("   printf: #0o0 '%#0.0o'\n", a);
//	 ft_printf("ft_printf: #0o0 '%#0.0o'\n", a);
//	 printf("   printf: o2 '%.2o'\n", a);
//	 ft_printf("ft_printf: o2 '%.2o'\n", a);
//	 printf("   printf: 2o2 '%2.2o'\n", a);
//	 ft_printf("ft_printf: 2o2 '%2.2o'\n", a);
//	 printf("   printf: -2o2 '%-2.2o'\n", a);
//	 ft_printf("ft_printf: -2o2 '%-2.2o'\n", a);
//	 printf("   printf: 02o2 '%02.2o'\n", a);
//	 ft_printf("ft_printf: 02o2 '%02.2o'\n", a);
//	 printf("   printf: #o2 '%#.2o'\n", a);
//	 ft_printf("ft_printf: #o2 '%#.2o'\n", a);
//	 printf("   printf: #2o2 '%#2.2o'\n", a);
//	 ft_printf("ft_printf: #2o2 '%#2.2o'\n", a);
//	 printf("   printf: #7o2 '%#7.2o'\n", a);
//	 ft_printf("ft_printf: #7o2 '%#7.2o'\n", a);
//	 printf("   printf: #-7o2 '%#-7.2o'\n", a);
//	 ft_printf("ft_printf: #-7o2 '%#-7.2o'\n", a);
//	 printf("   printf: o5 '%.5o'\n", a);
//	 ft_printf("ft_printf: o5 '%.5o'\n", a);
//	 printf("   printf: 14o5 '%14.5o'\n", a);
//	 ft_printf("ft_printf: 14o5 '%14.5o'\n", a);
//	 printf("   printf: -14o5 '%-14.5o'\n", a);
//	 ft_printf("ft_printf: -14o5 '%-14.5o'\n", a);
//	 printf("   printf: 014o5 '%014.5o'\n", a);
//	 ft_printf("ft_printf: 014o5 '%014.5o'\n", a);
//	 printf("   printf: #o5 '%#.5o'\n", a);
//	 ft_printf("ft_printf: #o5 '%#.5o'\n", a);
//	 printf("   printf: #14o5 '%#14.5o'\n", a);
//	 ft_printf("ft_printf: #14o5 '%#14.5o'\n", a);
//	 printf("   printf: #-14o5 '%#-14.5o'\n", a);
//	 ft_printf("ft_printf: #-14o5 '%#-14.5o'\n", a);
//	 printf("   printf: #014o5 '%#014.5o'\n", a);
//	 ft_printf("ft_printf: #014o5 '%#014.5o'\n", a);
//	 printf("   printf: o9 '%.9o'\n", a);
//	 ft_printf("ft_printf: o9 '%.9o'\n", a);
//	 printf("   printf: o9 '%0.9o'\n", a);
//	 ft_printf("ft_printf: o9 '%0.9o'\n", a);
//	 printf("   printf: #o9 '%#.9o'\n", a);
//	 ft_printf("ft_printf: #o9 '%#.9o'\n", a);
//	 printf("   printf: ho9 '%.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: ho9 '%.9ho'\n", ushort_a);
//	 printf("   printf: 9ho9 '%9.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: 9ho9 '%9.9ho'\n", ushort_a);
//	 printf("   printf: -9ho9 '%-9.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: -9ho9 '%-9.9ho'\n", ushort_a);
//	 printf("   printf: 09ho9 '%09.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: 09ho9 '%09.9ho'\n", ushort_a);
//	 printf("   printf: 15ho9 '%15.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: 15ho9 '%15.9ho'\n", ushort_a);
//	 printf("   printf: -15ho9 '%-15.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: -15ho9 '%-15.9ho'\n", ushort_a);
//	 printf("   printf: 015ho9 '%015.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: 015ho9 '%015.9ho'\n", ushort_a);
//	 printf("   printf: #ho9 '%#.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: #ho9 '%#.9ho'\n", ushort_a);
//	 printf("   printf: #2ho9 '%#2.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: #2ho9 '%#2.9ho'\n", ushort_a);
//	 printf("   printf: #-2ho9 '%#-2.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: #-2ho9 '%#-2.9ho'\n", ushort_a);
//	 printf("   printf: #12ho9 '%#12.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: #12ho9 '%#12.9ho'\n", ushort_a);
//	 printf("   printf: #-12ho9 '%#-12.9ho'\n", ushort_a);
//	 ft_printf("ft_printf: #-12ho9 '%#-12.9ho'\n", ushort_a);
//	 printf("   printf: #012ho9 '%#012.9ho'\n", ushort_a);
//     ft_printf("ft_printf: #012ho9 '%#012.9ho'\n", ushort_a);
//	 printf("   printf: hho9 '%.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: hho9 '%.9hho'\n", uchar_a);
//	 printf("   printf: 9hho9 '%9.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: 9hho9 '%9.9hho'\n", uchar_a);
//	 printf("   printf: -9hho9 '%-9.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: -9hho9 '%-9.9hho'\n", uchar_a);
//	 printf("   printf: 09hho9 '%09.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: 09hho9 '%09.9hho'\n", uchar_a);
//	 printf("   printf: 13hho9 '%13.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: 13hho9 '%13.9hho'\n", uchar_a);
//	 printf("   printf: -13hho9 '%-13.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: -13hho9 '%-13.9hho'\n", uchar_a);
//	 printf("   printf: 013hho9 '%013.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: 013hho9 '%013.9hho'\n", uchar_a);
//	 printf("   printf: #hho9 '%#.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: #hho9 '%#.9hho'\n", uchar_a);
//	 printf("   printf: #9hho9 '%#9.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: #9hho9 '%#9.9hho'\n", uchar_a);
//	 printf("   printf: #-9hho9 '%#-9.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: #-9hho9 '%#-9.9hho'\n", uchar_a);
//	 printf("   printf: #09hho9 '%#09.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: #09hho9 '%#09.9hho'\n", uchar_a);
//	 printf("   printf: #26hho9 '%#26.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: #26hho9 '%#26.9hho'\n", uchar_a);
//	 printf("   printf: #-26hho9 '%#-26.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: #-26hho9 '%#-26.9hho'\n", uchar_a);
//	 printf("   printf: #26hho9 '%#026.9hho'\n", uchar_a);
//	 ft_printf("ft_printf: #26hho9 '%#026.9hho'\n", uchar_a);
//	 printf("   printf: lo9 '%.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: lo9 '%.9lo'\n", ulong_a);
//	 printf("   printf: 9lo9 '%9.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: 9lo9 '%9.9lo'\n", ulong_a);
//	 printf("   printf: -9lo9 '%-9.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: -9lo9 '%-9.9lo'\n", ulong_a);
//	 printf("   printf: 09lo9 '%09.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: 09lo9 '%09.9lo'\n", ulong_a);
//	 printf("   printf: 27lo9 '%27.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: 27lo9 '%27.9lo'\n", ulong_a);
//	 printf("   printf: -27lo9 '%-27.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: -27lo9 '%-27.9lo'\n", ulong_a);
//	 printf("   printf: 027lo9 '%027.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: 027lo9 '%027.9lo'\n", ulong_a);
//	 printf("   printf: #lo9 '%#.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: #lo9 '%#.9lo'\n", ulong_a);
//	 printf("   printf: #9lo9 '%#9.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: #9lo9 '%#9.9lo'\n", ulong_a);
//	 printf("   printf: #-9lo9 '%#-9.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: #-9lo9 '%#-9.9lo'\n", ulong_a);
//	 printf("   printf: #09lo9 '%#09.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: #09lo9 '%#09.9lo'\n", ulong_a);
//	 printf("   printf: #24lo9 '%#24.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: #24lo9 '%#24.9lo'\n", ulong_a);
//	 printf("   printf: #-24lo9 '%#-24.9lo'\n", ulong_a);
//	 ft_printf("ft_printf: #-24lo9 '%#-24.9lo'\n", ulong_a);
//	 printf("   printf: llo9 '%.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: llo9 '%.9llo'\n", ullong_a);
//	 printf("   printf: 9llo9 '%9.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: 9llo9 '%9.9llo'\n", ullong_a);
//	 printf("   printf: -9llo9 '%-9.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: -9llo9 '%-9.9llo'\n", ullong_a);
//	 printf("   printf: 09llo9 '%09.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: 09llo9 '%09.9llo'\n", ullong_a);
//	 printf("   printf: 12llo9 '%12.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: 12llo9 '%12.9llo'\n", ullong_a);
//	 printf("   printf: -26llo9 '%-26.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: -26llo9 '%-26.9llo'\n", ullong_a);
//	 printf("   printf: 012llo9 '%012.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: 012llo9 '%012.9llo'\n", ullong_a);
//	 printf("   printf: #llo9 '%#.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: #llo9 '%#.9llo'\n", ullong_a);
//	 printf("   printf: #9llo9 '%#9.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: #9llo9 '%#9.9llo'\n", ullong_a);
//	 printf("   printf: #-9llo9 '%#-9.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: #-9llo9 '%#-9.9llo'\n", ullong_a);
//	 printf("   printf: #09llo9 '%#09.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: #09llo9 '%#09.9llo'\n", ullong_a);
//	 printf("   printf: #25llo9 '%#25.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: #25llo9 '%#25.9llo'\n", ullong_a);
//	 printf("   printf: #-25llo9 '%#-25.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: #-25llo9 '%#-25.9llo'\n", ullong_a);
//	 printf("   printf: #025llo9 '%#025.9llo'\n", ullong_a);
//	 ft_printf("ft_printf: #025llo9 '%#025.9llo'\n", ullong_a);
//
//
//	 printf(" <- Char count: %d\n", printf("   printf: <%o>", i));
//	 printf(" <- Char count: %d\n", ft_printf("ft_printf: <%o>", i));
//	 printf(" <- Char count: %d\n", printf("   printf: <%lo>", l));
//	 printf(" <- Char count: %d\n", ft_printf("ft_printf: <%lo>", l));
//	 printf(" <- Char count: %d\n", printf("   printf: <%llo>", ll));
//	 printf(" <- Char count: %d\n", ft_printf("ft_printf: <%llo>", ll));
//	 printf(" <- Char count: %d\n", printf("   printf: <%#.o>", 0));
//	 printf(" <- Char count: %d\n", ft_printf("ft_printf: <%#.o>", 0));
//	 printf(" <- Char count: %d\n", printf("   printf: <%o, %ho, %hho>", -42, -42, -42));
//	 printf(" <- Char count: %d\n", ft_printf("ft_printf: <%o, %ho, %hho>", -42, -42, -42));
//	 printf("   printf: u '%u'\n", a);
//	 ft_printf("ft_printf: u '%u'\n", a);
//	 printf("   printf: 5u '%5u'\n", a);
//	 ft_printf("ft_printf: 5u '%5u'\n", a);
//	 printf("   printf: -5u '%-5u'\n", a);
//	 ft_printf("ft_printf: -5u '%-5u'\n", a);
//	 printf("   printf: 05u '%05u'\n", a);
//	 ft_printf("ft_printf: 05u '%05u'\n", a);
//	 printf("   printf: 7u '%7u'\n", a);
//	 ft_printf("ft_printf: 7u '%7u'\n", a);
//	 printf("   printf: -7u '%-7u'\n", a);
//	 ft_printf("ft_printf: -7u '%-7u'\n", a);
//	 printf("   printf: 12u '%12u'\n", a);
//	 ft_printf("ft_printf: 12u '%12u'\n", a);
//	 printf("   printf: -12u '%-12u'\n", a);
//	 ft_printf("ft_printf: -12u '%-12u'\n", a);
//	 printf("   printf: 012u '%012u'\n", a);
//	 ft_printf("ft_printf: 012u '%012u'\n", a);
//	 printf("   printf: hu '%hu'\n", ushort_a);
//	 ft_printf("ft_printf: hu '%hu'\n", ushort_a);
//	 printf("   printf: 9hu '%9hu'\n", ushort_a);
//	 ft_printf("ft_printf: 9hu '%9hu'\n", ushort_a);
//	 printf("   printf: -9hu '%-9hu'\n", ushort_a);
//	 ft_printf("ft_printf: -9hu '%-9hu'\n", ushort_a);
//	 printf("   printf: 09hu '%09hu'\n", ushort_a);
//	 ft_printf("ft_printf: 09hu '%09hu'\n", ushort_a);
//	 printf("   printf: hhu '%hhu'\n", uchar_a);
//	 ft_printf("ft_printf: hhu '%hhu'\n", uchar_a);
//	 printf("   printf: 9hhu '%9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: 9hhu '%9hhu'\n", uchar_a);
//	 printf("   printf: -9hhu '%-9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: -9hhu '%-9hhu'\n", uchar_a);
//	 printf("   printf: 09hhu '%09hhu'\n", uchar_a);
//	 ft_printf("ft_printf: 09hhu '%09hhu'\n", uchar_a);
//	 printf("   printf: lu '%lu'\n", ulong_a);
//	 ft_printf("ft_printf: lu '%lu'\n", ulong_a);
//	 printf("   printf: 9lu '%9lu'\n", ulong_a);
//	 ft_printf("ft_printf: 9lu '%9lu'\n", ulong_a);
//	 printf("   printf: -9lu '%-9lu'\n", ulong_a);
//	 ft_printf("ft_printf: -9lu '%-9lu'\n", ulong_a);
//	 printf("   printf: 09lu '%09lu'\n", ulong_a);
//	 ft_printf("ft_printf: 09lu '%09lu'\n", ulong_a);
//	 printf("   printf: llu '%llu'\n", ullong_a);
//	 ft_printf("ft_printf: llu '%llu'\n", ullong_a);
//	 printf("   printf: 9llu '%9llu'\n", ullong_a);
//	 ft_printf("ft_printf: 9llu '%9llu'\n", ullong_a);
//	 printf("   printf: -9llu '%-9llu'\n", ullong_a);
//	 ft_printf("ft_printf: -9llu '%-9llu'\n", ullong_a);
//	 printf("   printf: 09llu '%09llu'\n", ullong_a);
//	 ft_printf("ft_printf: 09llu '%09llu'\n", ullong_a);
//	 printf("   printf: u0 '%.0u'\n", a);
//	 ft_printf("ft_printf: u0 '%.0u'\n", a);
//	 printf("   printf: u2 '%.2u'\n", a);
//	 ft_printf("ft_printf: u2 '%.2u'\n", a);
//	 printf("   printf: 2u2 '%2.2u'\n", a);
//	 ft_printf("ft_printf: 2u2 '%2.2u'\n", a);
//	 printf("   printf: 02u2 '%02.2u'\n", a);
//	 ft_printf("ft_printf: 02u2 '%02.2u'\n", a);
//	 printf("   printf: 7u2 '%7.2u'\n", a);
//	 ft_printf("ft_printf: 7u2 '%7.2u'\n", a);
//	 printf("   printf: -7u2 '%-7.2u'\n", a);
//	 ft_printf("ft_printf: -7u2 '%-7.2u'\n", a);
//	 printf("   printf: 07u2 '%07.2u'\n", a);
//	 ft_printf("ft_printf: 07u2 '%07.2u'\n", a);
//	 printf("   printf: u5 '%.5u'\n", a);
//	 ft_printf("ft_printf: u5 '%.5u'\n", a);
//	 printf("   printf: u9 '%.9u'\n", a);
//	 ft_printf("ft_printf: u9 '%.9u'\n", a);
//	 printf("   printf: 9u9 '%9.9u'\n", a);
//	 ft_printf("ft_printf: 9u9 '%9.9u'\n", a);
//	 printf("   printf: -9u9 '%-9.9u'\n", a);
//	 ft_printf("ft_printf: -9u9 '%-9.9u'\n", a);
//	 printf("   printf: 09u9 '%09.9u'\n", a);
//	 ft_printf("ft_printf: 09u9 '%09.9u'\n", a);
//	 printf("   printf: 12u9 '%12.9u'\n", a);
//	 ft_printf("ft_printf: 12u9 '%12.9u'\n", a);
//	 printf("   printf: -12u9 '%-12.9u'\n", a);
//	 ft_printf("ft_printf: -12u9 '%-12.9u'\n", a);
//	 printf("   printf: 012u9 '%012.9u'\n", a);
//	 ft_printf("ft_printf: 012u9 '%012.9u'\n", a);
//	 printf("   printf: hu9 '%.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: hu9 '%.9hu'\n", ushort_a);
//	 printf("   printf: 4hu9 '%4.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: 4hu9 '%4.9hu'\n", ushort_a);
//	 printf("   printf: -4hu9 '%-4.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: -4hu9 '%-4.9hu'\n", ushort_a);
//	 printf("   printf: 04hu9 '%04.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: 04hu9 '%04.9hu'\n", ushort_a);
//	 printf("   printf: 9hu9 '%9.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: 9hu9 '%9.9hu'\n", ushort_a);
//	 printf("   printf: -9hu9 '%-9.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: -9hu9 '%-9.9hu'\n", ushort_a);
//	 printf("   printf: 09hu9 '%09.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: 09hu9 '%09.9hu'\n", ushort_a);
//	 printf("   printf: 14hu9 '%14.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: 14hu9 '%14.9hu'\n", ushort_a);
//	 printf("   printf: -14hu9 '%-14.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: -14hu9 '%-14.9hu'\n", ushort_a);
//	 printf("   printf: 014hu9 '%014.9hu'\n", ushort_a);
//	 ft_printf("ft_printf: 014hu9 '%014.9hu'\n", ushort_a);
//	 printf("   printf: hhu9 '%.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: hhu9 '%.9hhu'\n", uchar_a);
//	 printf("   printf: 4hhu9 '%4.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: 4hhu9 '%4.9hhu'\n", uchar_a);
//	 printf("   printf: -4hhu9 '%-4.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: -4hhu9 '%-4.9hhu'\n", uchar_a);
//	 printf("   printf: 04hhu9 '%04.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: 04hhu9 '%04.9hhu'\n", uchar_a);
//	 printf("   printf: 9hhu9 '%9.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: 9hhu9 '%9.9hhu'\n", uchar_a);
//	 printf("   printf: -9hhu9 '%-9.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: -9hhu9 '%-9.9hhu'\n", uchar_a);
//	 printf("   printf: 09hhu9 '%09.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: 09hhu9 '%09.9hhu'\n", uchar_a);
//	 printf("   printf: 13hhu9 '%13.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: 13hhu9 '%13.9hhu'\n", uchar_a);
//	 printf("   printf: -13hhu9 '%-13.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: -13hhu9 '%-13.9hhu'\n", uchar_a);
//	 printf("   printf: 013hhu9 '%013.9hhu'\n", uchar_a);
//	 ft_printf("ft_printf: 013hhu9 '%013.9hhu'\n", uchar_a);
//	 printf("   printf: lu9 '%.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: lu9 '%.9lu'\n", ulong_a);
//	 printf("   printf: 4lu9 '%4.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: 4lu9 '%4.9lu'\n", ulong_a);
//	 printf("   printf: -4lu9 '%-4.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: -4lu9 '%-4.9lu'\n", ulong_a);
//	 printf("   printf: 04lu9 '%04.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: 04lu9 '%04.9lu'\n", ulong_a);
//	 printf("   printf: 9lu9 '%9.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: 9lu9 '%9.9lu'\n", ulong_a);
//	 printf("   printf: -9lu9 '%-9.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: -9lu9 '%-9.9lu'\n", ulong_a);
//	 printf("   printf: 09lu9 '%09.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: 09lu9 '%09.9lu'\n", ulong_a);
//	 printf("   printf: 25lu9 '%25.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: 25lu9 '%25.9lu'\n", ulong_a);
//	 printf("   printf: -25lu9 '%-25.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: -25lu9 '%-25.9lu'\n", ulong_a);
//	 printf("   printf: 025lu9 '%025.9lu'\n", ulong_a);
//	 ft_printf("ft_printf: 025lu9 '%025.9lu'\n", ulong_a);
//	 printf("   printf: llu9 '%.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: llu9 '%.9llu'\n", ullong_a);
//	 printf("   printf: 4llu9 '%4.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: 4llu9 '%4.9llu'\n", ullong_a);
//	 printf("   printf: -4llu9 '%-4.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: -4llu9 '%-4.9llu'\n", ullong_a);
//	 printf("   printf: 04llu9 '%04.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: 04llu9 '%04.9llu'\n", ullong_a);
//	 printf("   printf: 9llu9 '%9.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: 9llu9 '%9.9llu'\n", ullong_a);
//	 printf("   printf: -9llu9 '%-9.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: -9llu9 '%-9.9llu'\n", ullong_a);
//	 printf("   printf: 25llu9 '%25.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: 25llu9 '%25.9llu'\n", ullong_a);
//	 printf("   printf: -25llu9 '%-25.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: -25llu9 '%-25.9llu'\n", ullong_a);
//	 printf("   printf: 025llu9 '%025.9llu'\n", ullong_a);
//	 ft_printf("ft_printf: 025llu9 '%025.9llu'\n", ullong_a);
//
//	 printf("   printf: x '%x'\n", a);
//	 ft_printf("ft_printf: x '%x'\n", a);
//	 printf("   printf: 10x '%10x'\n", a);
//	 ft_printf("ft_printf: 10x '%10x'\n", a);
//	 printf("   printf: -10x '%-10x'\n", a);
//	 ft_printf("ft_printf: -10x '%-10x'\n", a);
//	 printf("   printf: 010x '%010x'\n", a);
//	 ft_printf("ft_printf: 010x '%010x'\n", a);
//	 printf("   printf: #x '%#x'\n", a);
//	 ft_printf("ft_printf: #x '%#x'\n", a);
//	 printf("   printf: #10x '%#10x'\n", a);
//	 ft_printf("ft_printf: #10x '%#10x'\n", a);
//	 printf("   printf: #-10x '%#-10x'\n", a);
//	 ft_printf("ft_printf: #-10x '%#-10x'\n", a);
//	 printf("   printf: #010x '%#010x'\n", a);
//	 ft_printf("ft_printf: #010x '%#010x'\n", a);
//	 printf("   printf: hx '%hx'\n", ushort_a);
//	 ft_printf("ft_printf: hx '%hx'\n", ushort_a);
//	 printf("   printf: 15hx '%15hx'\n", ushort_a);
//	 ft_printf("ft_printf: 15hx '%15hx'\n", ushort_a);
//	 printf("   printf: -15hx '%-15hx'\n", ushort_a);
//	 ft_printf("ft_printf: -15hx '%-15hx'\n", ushort_a);
//	 printf("   printf: 015hx '%015hx'\n", ushort_a);
//	 ft_printf("ft_printf: 015hx '%015hx'\n", ushort_a);
//	 printf("   printf: #hx '%#hx'\n", ushort_a);
//	 ft_printf("ft_printf: #hx '%#hx'\n", ushort_a);
//	 printf("   printf: #20hx '%#20hx'\n", ushort_a);
//	 ft_printf("ft_printf: #20hx '%#20hx'\n", ushort_a);
//	 printf("   printf: #-20hx '%#-20hx'\n", ushort_a);
//	 ft_printf("ft_printf: #-20hx '%#-20hx'\n", ushort_a);
//	 printf("   printf: #020hx '%#020hx'\n", ushort_a);
//	 ft_printf("ft_printf: #020hx '%#020hx'\n", ushort_a);
//	 printf("   printf: hhx '%hhx'\n", uchar_a);
//	 ft_printf("ft_printf: hhx '%hhx'\n", uchar_a);
//	 printf("   printf: 20hhx '%20hhx'\n", uchar_a);
//	 ft_printf("ft_printf: 20hhx '%20hhx'\n", uchar_a);
//	 printf("   printf: -20hhx '%-20hhx'\n", uchar_a);
//	 ft_printf("ft_printf: -20hhx '%-20hhx'\n", uchar_a);
//	 printf("   printf: 020hhx '%020hhx'\n", uchar_a);
//	 ft_printf("ft_printf: 020hhx '%020hhx'\n", uchar_a);
//	 printf("   printf: #hhx '%#hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #hhx '%#hhx'\n", uchar_a);
//	 printf("   printf: #20hhx '%#20hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #20hhx '%#20hhx'\n", uchar_a);
//	 printf("   printf: #-20hhx '%#-20hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #-20hhx '%#-20hhx'\n", uchar_a);
//	 printf("   printf: #020hhx '%#020hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #020hhx '%#020hhx'\n", uchar_a);
//	 printf("   printf: lx '%lx'\n", ulong_a);
//	 ft_printf("ft_printf: lx '%lx'\n", ulong_a);
//	 printf("   printf: 20lx '%20lx'\n", ulong_a);
//	 ft_printf("ft_printf: 20lx '%20lx'\n", ulong_a);
//	 printf("   printf: -20lx '%-20lx'\n", ulong_a);
//	 ft_printf("ft_printf: -20lx '%-20lx'\n", ulong_a);
//	 printf("   printf: 020lx '%020lx'\n", ulong_a);
//	 ft_printf("ft_printf: 020lx '%020lx'\n", ulong_a);
//	 printf("   printf: #lx '%#lx'\n", ulong_a);
//	 ft_printf("ft_printf: #lx '%#lx'\n", ulong_a);
//	 printf("   printf: #20lx '%#20lx'\n", ulong_a);
//	 ft_printf("ft_printf: #20lx '%#20lx'\n", ulong_a);
//	 printf("   printf: #-20lx '%#-20lx'\n", ulong_a);
//	 ft_printf("ft_printf: #-20lx '%#-20lx'\n", ulong_a);
//	 printf("   printf: #020lx '%#020lx'\n", ulong_a);
//	 ft_printf("ft_printf: #020lx '%#020lx'\n", ulong_a);
//	 printf("   printf: llx '%llx'\n", ullong_a);
//	 ft_printf("ft_printf: llx '%llx'\n", ullong_a);
//	 printf("   printf: 20llx '%20llx'\n", ullong_a);
//	 ft_printf("ft_printf: 20llx '%20llx'\n", ullong_a);
//	 printf("   printf: -20llx '%-20llx'\n", ullong_a);
//	 ft_printf("ft_printf: -20llx '%-20llx'\n", ullong_a);
//	 printf("   printf: 020llx '%020llx'\n", ullong_a);
//	 ft_printf("ft_printf: 020llx '%020llx'\n", ullong_a);
//	 printf("   printf: #llx '%#llx'\n", ullong_a);
//	 ft_printf("ft_printf: #llx '%#llx'\n", ullong_a);
//	 printf("   printf: #20llx '%#20llx'\n", ullong_a);
//	 ft_printf("ft_printf: #20llx '%#20llx'\n", ullong_a);
//	 printf("   printf: #-20llx '%#-20llx'\n", ullong_a);
//	 ft_printf("ft_printf: #-20llx '%#-20llx'\n", ullong_a);
//	 printf("   printf: #020llx '%#020llx'\n", ullong_a);
//	 ft_printf("ft_printf: #020llx '%#020llx'\n", ullong_a);
//	 printf("   printf: x0 '%.0x'\n", a);
//	 ft_printf("ft_printf: x0 '%.0x'\n", a);
//	 printf("   printf: 2x0 '%2.0x'\n", a);
//	 ft_printf("ft_printf: 2x0 '%2.0x'\n", a);
//	 printf("   printf: -2x0 '%-2.0x'\n", a);
//	 ft_printf("ft_printf: -2x0 '%-2.0x'\n", a);
//	 printf("   printf: #x0 '%#.0x'\n", a);
//	 ft_printf("ft_printf: #x0 '%#.0x'\n", a);
//	 printf("   printf: #2x0 '%#2.0x'\n", a);
//	 ft_printf("ft_printf: #2x0 '%#2.0x'\n", a);
//	 printf("   printf: #-2x0 '%#-2.0x'\n", a);
//	 ft_printf("ft_printf: #-2x0 '%#-2.0x'\n", a);
//	 printf("   printf: #02x0 '%#02.0x'\n", a);
//	 ft_printf("ft_printf: #02x0 '%#02.0x'\n", a);
//	 printf("   printf: x2 '%.2x'\n", a);
//	 ft_printf("ft_printf: x2 '%.2x'\n", a);
//	 printf("   printf: #x2 '%#.2x'\n", a);
//	 ft_printf("ft_printf: #x2 '%#.2x'\n", a);
//	 printf("   printf: x5 '%.5x'\n", a);
//	 ft_printf("ft_printf: x5 '%.5x'\n", a);
//	 printf("   printf: #x5 '%#.5x'\n", a);
//	 ft_printf("ft_printf: #x5 '%#.5x'\n", a);
//	 printf("   printf: x9 '%.9x'\n", a);
//	 ft_printf("ft_printf: x9 '%.9x'\n", a);
//	 printf("   printf: 4x9 '%4.9x'\n", a);
//	 ft_printf("ft_printf: 4x9 '%4.9x'\n", a);
//	 printf("   printf: -4x9 '%-4.9x'\n", a);
//	 ft_printf("ft_printf: -4x9 '%-4.9x'\n", a);
//	 printf("   printf: 04x9 '%04.9x'\n", a);
//	 ft_printf("ft_printf: 04x9 '%04.9x'\n", a);
//	 printf("   printf: 9x9 '%9.9x'\n", a);
//	 ft_printf("ft_printf: 9x9 '%9.9x'\n", a);
//	 printf("   printf: -9x9 '%-9.9x'\n", a);
//	 ft_printf("ft_printf: -9x9 '%-9.9x'\n", a);
//	 printf("   printf: 09x9 '%09.9x'\n", a);
//	 ft_printf("ft_printf: 09x9 '%09.9x'\n", a);
//	 printf("   printf: 15x9 '%15.9x'\n", a);
//	 ft_printf("ft_printf: 15x9 '%15.9x'\n", a);
//	 printf("   printf: -15x9 '%-15.9x'\n", a);
//	 ft_printf("ft_printf: -15x9 '%-15.9x'\n", a);
//	 printf("   printf: 015x9 '%015.9x'\n", a);
//	 ft_printf("ft_printf: 015x9 '%015.9x'\n", a);
//	 printf("   printf: #x9 '%#.9x'\n", a);
//	 ft_printf("ft_printf: #x9 '%#.9x'\n", a);
//	 printf("   printf: #4x9 '%#4.9x'\n", a);
//	 ft_printf("ft_printf: #4x9 '%#4.9x'\n", a);
//	 printf("   printf: #-4x9 '%#-4.9x'\n", a);
//	 ft_printf("ft_printf: #-4x9 '%#-4.9x'\n", a);
//	 printf("   printf: #04x9 '%#04.9x'\n", a);
//	 ft_printf("ft_printf: #04x9 '%#04.9x'\n", a);
//	 printf("   printf: #9x9 '%#9.9x'\n", a);
//	 ft_printf("ft_printf: #9x9 '%#9.9x'\n", a);
//	 printf("   printf: #-9x9 '%#-9.9x'\n", a);
//	 ft_printf("ft_printf: #-9x9 '%#-9.9x'\n", a);
//	 printf("   printf: #09x9 '%#09.9x'\n", a);
//	 ft_printf("ft_printf: #09x9 '%#09.9x'\n", a);
//	 printf("   printf: #15x9 '%#15.9x'\n", a);
//	 ft_printf("ft_printf: #15x9 '%#15.9x'\n", a);
//	 printf("   printf: #-15x9 '%#-15.9x'\n", a);
//	 ft_printf("ft_printf: #-15x9 '%#-15.9x'\n", a);
//	 printf("   printf: #015x9 '%#015.9x'\n", a);
//	 ft_printf("ft_printf: #015x9 '%#015.9x'\n", a);
//	 printf("   printf: hx9 '%.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: hx9 '%.9hx'\n", ushort_a);
//	 printf("   printf: 4hx9 '%4.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: 4hx9 '%4.9hx'\n", ushort_a);
//	 printf("   printf: -4hx9 '%-4.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: -4hx9 '%-4.9hx'\n", ushort_a);
//	 printf("   printf: 04hx9 '%04.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: 04hx9 '%04.9hx'\n", ushort_a);
//	 printf("   printf: 9hx9 '%9.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: 9hx9 '%9.9hx'\n", ushort_a);
//	 printf("   printf: -9hx9 '%-9.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: -9hx9 '%-9.9hx'\n", ushort_a);
//	 printf("   printf: 09hx9 '%09.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: 09hx9 '%09.9hx'\n", ushort_a);
//	 printf("   printf: 20hx9 '%20.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: 20hx9 '%20.9hx'\n", ushort_a);
//	 printf("   printf: -20hx9 '%-20.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: -20hx9 '%-20.9hx'\n", ushort_a);
//	 printf("   printf: 020hx9 '%020.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: 020hx9 '%020.9hx'\n", ushort_a);
//	 printf("   printf: #hx9 '%#.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #hx9 '%#.9hx'\n", ushort_a);
//	 printf("   printf: #4hx9 '%#4.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #4hx9 '%#4.9hx'\n", ushort_a);
//	 printf("   printf: #-4hx9 '%#-4.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #-4hx9 '%#-4.9hx'\n", ushort_a);
//	 printf("   printf: #04hx9 '%#04.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #04hx9 '%#04.9hx'\n", ushort_a);
//	 printf("   printf: #9hx9 '%#9.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #9hx9 '%#9.9hx'\n", ushort_a);
//	 printf("   printf: #-9hx9 '%#-9.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #-9hx9 '%#-9.9hx'\n", ushort_a);
//	 printf("   printf: #09hx9 '%#09.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #09hx9 '%#09.9hx'\n", ushort_a);
//	 printf("   printf: #20hx9 '%#20.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #20hx9 '%#20.9hx'\n", ushort_a);
//	 printf("   printf: #-20hx9 '%#-20.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #-20hx9 '%#-20.9hx'\n", ushort_a);
//	 printf("   printf: #020hx9 '%#020.9hx'\n", ushort_a);
//	 ft_printf("ft_printf: #020hx9 '%#020.9hx'\n", ushort_a);
//	 printf("   printf: hhx9 '%.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: hhx9 '%.9hhx'\n", uchar_a);
//	 printf("   printf: 4hhx9 '%4.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: 4hhx9 '%4.9hhx'\n", uchar_a);
//	 printf("   printf: -4hhx9 '%-4.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: -4hhx9 '%-4.9hhx'\n", uchar_a);
//	 printf("   printf: 04hhx9 '%04.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: 04hhx9 '%04.9hhx'\n", uchar_a);
//	 printf("   printf: 9hhx9 '%9.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: 9hhx9 '%9.9hhx'\n", uchar_a);
//	 printf("   printf: -9hhx9 '%-9.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: -9hhx9 '%-9.9hhx'\n", uchar_a);
//	 printf("   printf: 09hhx9 '%09.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: 09hhx9 '%09.9hhx'\n", uchar_a);
//	 printf("   printf: 20hhx9 '%20.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: 20hhx9 '%20.9hhx'\n", uchar_a);
//	 printf("   printf: -20hhx9 '%-20.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: -20hhx9 '%-20.9hhx'\n", uchar_a);
//	 printf("   printf: 020hhx9 '%020.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: 020hhx9 '%020.9hhx'\n", uchar_a);
//	 printf("   printf: #hhx9 '%#.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #hhx9 '%#.9hhx'\n", uchar_a);
//	 printf("   printf: #4hhx9 '%#4.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #4hhx9 '%#4.9hhx'\n", uchar_a);
//	 printf("   printf: #-4hhx9 '%#-4.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #-4hhx9 '%#-4.9hhx'\n", uchar_a);
//	 printf("   printf: #04hhx9 '%#04.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #04hhx9 '%#04.9hhx'\n", uchar_a);
//	 printf("   printf: #9hhx9 '%#9.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #9hhx9 '%#9.9hhx'\n", uchar_a);
//	 printf("   printf: #-9hhx9 '%#-9.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #-9hhx9 '%#-9.9hhx'\n", uchar_a);
//	 printf("   printf: #09hhx9 '%#09.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #09hhx9 '%#09.9hhx'\n", uchar_a);
//	 printf("   printf: #20hhx9 '%#20.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #20hhx9 '%#20.9hhx'\n", uchar_a);
//	 printf("   printf: #-20hhx9 '%#-20.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #-20hhx9 '%#-20.9hhx'\n", uchar_a);
//	 printf("   printf: #020hhx9 '%#020.9hhx'\n", uchar_a);
//	 ft_printf("ft_printf: #020hhx9 '%#020.9hhx'\n", uchar_a);
//	 printf("   printf: lx9 '%.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: lx9 '%.9lx'\n", ulong_a);
//	 printf("   printf: 4lx9 '%4.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: 4lx9 '%4.9lx'\n", ulong_a);
//	 printf("   printf: -4lx9 '%-4.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: -4lx9 '%-4.9lx'\n", ulong_a);
//	 printf("   printf: 04lx9 '%04.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: 04lx9 '%04.9lx'\n", ulong_a);
//	 printf("   printf: 9lx9 '%9.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: 9lx9 '%9.9lx'\n", ulong_a);
//	 printf("   printf: -9lx9 '%-9.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: -9lx9 '%-9.9lx'\n", ulong_a);
//	 printf("   printf: 09lx9 '%09.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: 09lx9 '%09.9lx'\n", ulong_a);
//	 printf("   printf: 20lx9 '%20.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: 20lx9 '%20.9lx'\n", ulong_a);
//	 printf("   printf: -20lx9 '%-20.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: -20lx9 '%-20.9lx'\n", ulong_a);
//	 printf("   printf: 020lx9 '%020.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: 020lx9 '%020.9lx'\n", ulong_a);
//	 printf("   printf: #lx9 '%#.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #lx9 '%#.9lx'\n", ulong_a);
//	 printf("   printf: #4lx9 '%#4.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #4lx9 '%#4.9lx'\n", ulong_a);
//	 printf("   printf: #-4lx9 '%#-4.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #-4lx9 '%#-4.9lx'\n", ulong_a);
//	 printf("   printf: #04lx9 '%#04.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #04lx9 '%#04.9lx'\n", ulong_a);
//	 printf("   printf: #9lx9 '%#9.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #9lx9 '%#9.9lx'\n", ulong_a);
//	 printf("   printf: #-9lx9 '%#-9.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #-9lx9 '%#-9.9lx'\n", ulong_a);
//	 printf("   printf: #09lx9 '%#09.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #09lx9 '%#09.9lx'\n", ulong_a);
//	 printf("   printf: #20lx9 '%#20.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #20lx9 '%#20.9lx'\n", ulong_a);
//	 printf("   printf: #-20lx9 '%#-20.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #-20lx9 '%#-20.9lx'\n", ulong_a);
//	 printf("   printf: #020lx9 '%#020.9lx'\n", ulong_a);
//	 ft_printf("ft_printf: #020lx9 '%#020.9lx'\n", ulong_a);
//	 printf("   printf: llx9 '%.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: llx9 '%.9llx'\n", ullong_a);
//	 printf("   printf: 4llx9 '%4.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: 4llx9 '%4.9llx'\n", ullong_a);
//	 printf("   printf: -4llx9 '%-4.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: -4llx9 '%-4.9llx'\n", ullong_a);
//	 printf("   printf: 04llx9 '%04.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: 04llx9 '%04.9llx'\n", ullong_a);
//	 printf("   printf: 9llx9 '%9.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: 9llx9 '%9.9llx'\n", ullong_a);
//	 printf("   printf: -9llx9 '%-9.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: -9llx9 '%-9.9llx'\n", ullong_a);
//	 printf("   printf: 09llx9 '%09.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: 09llx9 '%09.9llx'\n", ullong_a);
//	 printf("   printf: 20llx9 '%20.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: 20llx9 '%20.9llx'\n", ullong_a);
//	 printf("   printf: -20llx9 '%-20.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: -20llx9 '%-20.9llx'\n", ullong_a);
//	 printf("   printf: 020llx9 '%020.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: 020llx9 '%020.9llx'\n", ullong_a);
//	 printf("   printf: #llx9 '%#.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #llx9 '%#.9llx'\n", ullong_a);
//	 printf("   printf: #4llx9 '%#4.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #4llx9 '%#4.9llx'\n", ullong_a);
//	 printf("   printf: #-4llx9 '%#-4.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #-4llx9 '%#-4.9llx'\n", ullong_a);
//	 printf("   printf: #04llx9 '%#04.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #04llx9 '%#04.9llx'\n", ullong_a);
//	 printf("   printf: #9llx9 '%#9.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #9llx9 '%#9.9llx'\n", ullong_a);
//	 printf("   printf: #-9llx9 '%#-9.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #-9llx9 '%#-9.9llx'\n", ullong_a);
//	 printf("   printf: #09llx9 '%#09.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #09llx9 '%#09.9llx'\n", ullong_a);
//	 printf("   printf: #20llx9 '%#20.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #20llx9 '%#20.9llx'\n", ullong_a);
//	 printf("   printf: #-20llx9 '%#-20.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #-20llx9 '%#-20.9llx'\n", ullong_a);
//	 printf("   printf: #020llx9 '%#020.9llx'\n", ullong_a);
//	 ft_printf("ft_printf: #020llx9 '%#020.9llx'\n", ullong_a);
//
//	 printf("   printf: X '%X'\n", a);
//	// ft_printf("ft_printf: X '%X'\n", a);
//	 printf("   printf: 10X '%10X'\n", a);
//	 ft_printf("ft_printf: 10X '%10X'\n", a);
//	 printf("   printf: -10X '%-10X'\n", a);
//	 ft_printf("ft_printf: -10X '%-10X'\n", a);
//	 printf("   printf: 010X '%010X'\n", a);
//	 ft_printf("ft_printf: 010X '%010X'\n", a);
//	 printf("   printf: #X '%#X'\n", a);
//	 ft_printf("ft_printf: #X '%#X'\n", a);
//	 printf("   printf: #10X '%#10X'\n", a);
//	 ft_printf("ft_printf: #10X '%#10X'\n", a);
//	 printf("   printf: #-10X '%#-10X'\n", a);
//	 ft_printf("ft_printf: #-10X '%#-10X'\n", a);
//	 printf("   printf: #010X '%#010X'\n", a);
//	 ft_printf("ft_printf: #010X '%#010X'\n", a);
//	 printf("   printf: hX '%hX'\n", ushort_a);
//	 ft_printf("ft_printf: hX '%hX'\n", ushort_a);
//	 printf("   printf: 15hX '%15hX'\n", ushort_a);
//	 ft_printf("ft_printf: 15hX '%15hX'\n", ushort_a);
//	 printf("   printf: -15hX '%-15hX'\n", ushort_a);
//	 ft_printf("ft_printf: -15hX '%-15hX'\n", ushort_a);
//	 printf("   printf: 015hX '%015hX'\n", ushort_a);
//	 ft_printf("ft_printf: 015hX '%015hX'\n", ushort_a);
//	 printf("   printf: #hX '%#hX'\n", ushort_a);
//	 ft_printf("ft_printf: #hX '%#hX'\n", ushort_a);
//	 printf("   printf: #20hX '%#20hX'\n", ushort_a);
//	 ft_printf("ft_printf: #20hX '%#20hX'\n", ushort_a);
//	 printf("   printf: #-20hX '%#-20hX'\n", ushort_a);
//	 ft_printf("ft_printf: #-20hX '%#-20hX'\n", ushort_a);
//	 printf("   printf: #020hX '%#020hX'\n", ushort_a);
//	 ft_printf("ft_printf: #020hX '%#020hX'\n", ushort_a);
//	 printf("   printf: hhX '%hhX'\n", uchar_a);
//	 ft_printf("ft_printf: hhX '%hhX'\n", uchar_a);
//	 printf("   printf: 20hhX '%20hhX'\n", uchar_a);
//	 ft_printf("ft_printf: 20hhX '%20hhX'\n", uchar_a);
//	 printf("   printf: -20hhX '%-20hhX'\n", uchar_a);
//	 ft_printf("ft_printf: -20hhX '%-20hhX'\n", uchar_a);
//	 printf("   printf: 020hhX '%020hhX'\n", uchar_a);
//	 ft_printf("ft_printf: 020hhX '%020hhX'\n", uchar_a);
//	 printf("   printf: #hhX '%#hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #hhX '%#hhX'\n", uchar_a);
//	 printf("   printf: #20hhX '%#20hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #20hhX '%#20hhX'\n", uchar_a);
//	 printf("   printf: #-20hhX '%#-20hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #-20hhX '%#-20hhX'\n", uchar_a);
//	 printf("   printf: #020hhX '%#020hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #020hhX '%#020hhX'\n", uchar_a);
//	 printf("   printf: lX '%lX'\n", ulong_a);
//	 ft_printf("ft_printf: lX '%lX'\n", ulong_a);
//	 printf("   printf: 20lX '%20lX'\n", ulong_a);
//	 ft_printf("ft_printf: 20lX '%20lX'\n", ulong_a);
//	 printf("   printf: -20lX '%-20lX'\n", ulong_a);
//	 ft_printf("ft_printf: -20lX '%-20lX'\n", ulong_a);
//	 printf("   printf: 020lX '%020lX'\n", ulong_a);
//	 ft_printf("ft_printf: 020lX '%020lX'\n", ulong_a);
//	 printf("   printf: #lX '%#lX'\n", ulong_a);
//	 ft_printf("ft_printf: #lX '%#lX'\n", ulong_a);
//	 printf("   printf: #20lX '%#20lX'\n", ulong_a);
//	 ft_printf("ft_printf: #20lX '%#20lX'\n", ulong_a);
//	 printf("   printf: #-20lX '%#-20lX'\n", ulong_a);
//	 ft_printf("ft_printf: #-20lX '%#-20lX'\n", ulong_a);
//	 printf("   printf: #020lX '%#020lX'\n", ulong_a);
//	 ft_printf("ft_printf: #020lX '%#020lX'\n", ulong_a);
//	 printf("   printf: llX '%llX'\n", ullong_a);
//	 ft_printf("ft_printf: llX '%llX'\n", ullong_a);
//	 printf("   printf: 20llX '%20llX'\n", ullong_a);
//	 ft_printf("ft_printf: 20llX '%20llX'\n", ullong_a);
//	 printf("   printf: -20llX '%-20llX'\n", ullong_a);
//	 ft_printf("ft_printf: -20llX '%-20llX'\n", ullong_a);
//	 printf("   printf: 020llX '%020llX'\n", ullong_a);
//	 ft_printf("ft_printf: 020llX '%020llX'\n", ullong_a);
//	 printf("   printf: #llX '%#llX'\n", ullong_a);
//	 ft_printf("ft_printf: #llX '%#llX'\n", ullong_a);
//	 printf("   printf: #20llX '%#20llX'\n", ullong_a);
//	 ft_printf("ft_printf: #20llX '%#20llX'\n", ullong_a);
//	 printf("   printf: #-20llX '%#-20llX'\n", ullong_a);
//	 ft_printf("ft_printf: #-20llX '%#-20llX'\n", ullong_a);
//	 printf("   printf: #020llX '%#020llX'\n", ullong_a);
//	 ft_printf("ft_printf: #020llX '%#020llX'\n", ullong_a);
//	 printf("   printf: X0 '%.0X'\n", a);
//	 ft_printf("ft_printf: X0 '%.0X'\n", a);
//	 printf("   printf: 2X0 '%2.0X'\n", a);
//	 ft_printf("ft_printf: 2X0 '%2.0X'\n", a);
//	 printf("   printf: -2X0 '%-2.0X'\n", a);
//	 ft_printf("ft_printf: -2X0 '%-2.0X'\n", a);
//	 printf("   printf: #X0 '%#.0X'\n", a);
//	 ft_printf("ft_printf: #X0 '%#.0X'\n", a);
//	 printf("   printf: #2X0 '%#2.0X'\n", a);
//	 ft_printf("ft_printf: #2X0 '%#2.0X'\n", a);
//	 printf("   printf: #-2X0 '%#-2.0X'\n", a);
//	 ft_printf("ft_printf: #-2X0 '%#-2.0X'\n", a);
//	 printf("   printf: #02X0 '%#02.0X'\n", a);
//	 ft_printf("ft_printf: #02X0 '%#02.0X'\n", a);
//	 printf("   printf: X2 '%.2X'\n", a);
//	 ft_printf("ft_printf: X2 '%.2X'\n", a);
//	 printf("   printf: #X2 '%#.2X'\n", a);
//	 ft_printf("ft_printf: #X2 '%#.2X'\n", a);
//	 printf("   printf: X5 '%.5X'\n", a);
//	 ft_printf("ft_printf: X5 '%.5X'\n", a);
//	 printf("   printf: #X5 '%#.5X'\n", a);
//	 ft_printf("ft_printf: #X5 '%#.5X'\n", a);
//	 printf("   printf: X9 '%.9X'\n", a);
//	 ft_printf("ft_printf: X9 '%.9X'\n", a);
//	 printf("   printf: 4X9 '%4.9X'\n", a);
//	 ft_printf("ft_printf: 4X9 '%4.9X'\n", a);
//	 printf("   printf: -4X9 '%-4.9X'\n", a);
//	 ft_printf("ft_printf: -4X9 '%-4.9X'\n", a);
//	 printf("   printf: 04X9 '%04.9X'\n", a);
//	 ft_printf("ft_printf: 04X9 '%04.9X'\n", a);
//	 printf("   printf: 9X9 '%9.9X'\n", a);
//	 ft_printf("ft_printf: 9X9 '%9.9X'\n", a);
//	 printf("   printf: -9X9 '%-9.9X'\n", a);
//	 ft_printf("ft_printf: -9X9 '%-9.9X'\n", a);
//	 printf("   printf: 09X9 '%09.9X'\n", a);
//	 ft_printf("ft_printf: 09X9 '%09.9X'\n", a);
//	 printf("   printf: 15X9 '%15.9X'\n", a);
//	 ft_printf("ft_printf: 15X9 '%15.9X'\n", a);
//	 printf("   printf: -15X9 '%-15.9X'\n", a);
//	 ft_printf("ft_printf: -15X9 '%-15.9X'\n", a);
//	 printf("   printf: 015X9 '%015.9X'\n", a);
//	 ft_printf("ft_printf: 015X9 '%015.9X'\n", a);
//	 printf("   printf: #X9 '%#.9X'\n", a);
//	 ft_printf("ft_printf: #X9 '%#.9X'\n", a);
//	 printf("   printf: #4X9 '%#4.9X'\n", a);
//	 ft_printf("ft_printf: #4X9 '%#4.9X'\n", a);
//	 printf("   printf: #-4X9 '%#-4.9X'\n", a);
//	 ft_printf("ft_printf: #-4X9 '%#-4.9X'\n", a);
//	 printf("   printf: #04X9 '%#04.9X'\n", a);
//	 ft_printf("ft_printf: #04X9 '%#04.9X'\n", a);
//	 printf("   printf: #9X9 '%#9.9X'\n", a);
//	 ft_printf("ft_printf: #9X9 '%#9.9X'\n", a);
//	 printf("   printf: #-9X9 '%#-9.9X'\n", a);
//	 ft_printf("ft_printf: #-9X9 '%#-9.9X'\n", a);
//	 printf("   printf: #09X9 '%#09.9X'\n", a);
//	 ft_printf("ft_printf: #09X9 '%#09.9X'\n", a);
//	 printf("   printf: #15X9 '%#15.9X'\n", a);
//	 ft_printf("ft_printf: #15X9 '%#15.9X'\n", a);
//	 printf("   printf: #-15X9 '%#-15.9X'\n", a);
//	 ft_printf("ft_printf: #-15X9 '%#-15.9X'\n", a);
//	 printf("   printf: #015X9 '%#015.9X'\n", a);
//	 ft_printf("ft_printf: #015X9 '%#015.9X'\n", a);
//	 printf("   printf: hX9 '%.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: hX9 '%.9hX'\n", ushort_a);
//	 printf("   printf: 4hX9 '%4.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: 4hX9 '%4.9hX'\n", ushort_a);
//	 printf("   printf: -4hX9 '%-4.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: -4hX9 '%-4.9hX'\n", ushort_a);
//	 printf("   printf: 04hX9 '%04.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: 04hX9 '%04.9hX'\n", ushort_a);
//	 printf("   printf: 9hX9 '%9.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: 9hX9 '%9.9hX'\n", ushort_a);
//	 printf("   printf: -9hX9 '%-9.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: -9hX9 '%-9.9hX'\n", ushort_a);
//	 printf("   printf: 09hX9 '%09.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: 09hX9 '%09.9hX'\n", ushort_a);
//	 printf("   printf: 20hX9 '%20.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: 20hX9 '%20.9hX'\n", ushort_a);
//	 printf("   printf: -20hX9 '%-20.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: -20hX9 '%-20.9hX'\n", ushort_a);
//	 printf("   printf: 020hX9 '%020.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: 020hX9 '%020.9hX'\n", ushort_a);
//	 printf("   printf: #hX9 '%#.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #hX9 '%#.9hX'\n", ushort_a);
//	 printf("   printf: #4hX9 '%#4.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #4hX9 '%#4.9hX'\n", ushort_a);
//	 printf("   printf: #-4hX9 '%#-4.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #-4hX9 '%#-4.9hX'\n", ushort_a);
//	 printf("   printf: #04hX9 '%#04.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #04hX9 '%#04.9hX'\n", ushort_a);
//	 printf("   printf: #9hX9 '%#9.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #9hX9 '%#9.9hX'\n", ushort_a);
//	 printf("   printf: #-9hX9 '%#-9.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #-9hX9 '%#-9.9hX'\n", ushort_a);
//	 printf("   printf: #09hX9 '%#09.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #09hX9 '%#09.9hX'\n", ushort_a);
//	 printf("   printf: #20hX9 '%#20.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #20hX9 '%#20.9hX'\n", ushort_a);
//	 printf("   printf: #-20hX9 '%#-20.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #-20hX9 '%#-20.9hX'\n", ushort_a);
//	 printf("   printf: #020hX9 '%#020.9hX'\n", ushort_a);
//	 ft_printf("ft_printf: #020hX9 '%#020.9hX'\n", ushort_a);
//	 printf("   printf: hhX9 '%.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: hhX9 '%.9hhX'\n", uchar_a);
//	 printf("   printf: 4hhX9 '%4.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: 4hhX9 '%4.9hhX'\n", uchar_a);
//	 printf("   printf: -4hhX9 '%-4.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: -4hhX9 '%-4.9hhX'\n", uchar_a);
//	 printf("   printf: 04hhX9 '%04.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: 04hhX9 '%04.9hhX'\n", uchar_a);
//	 printf("   printf: 9hhX9 '%9.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: 9hhX9 '%9.9hhX'\n", uchar_a);
//	 printf("   printf: -9hhX9 '%-9.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: -9hhX9 '%-9.9hhX'\n", uchar_a);
//	 printf("   printf: 09hhX9 '%09.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: 09hhX9 '%09.9hhX'\n", uchar_a);
//	 printf("   printf: 20hhX9 '%20.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: 20hhX9 '%20.9hhX'\n", uchar_a);
//	 printf("   printf: -20hhX9 '%-20.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: -20hhX9 '%-20.9hhX'\n", uchar_a);
//	 printf("   printf: 020hhX9 '%020.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: 020hhX9 '%020.9hhX'\n", uchar_a);
//	 printf("   printf: #hhX9 '%#.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #hhX9 '%#.9hhX'\n", uchar_a);
//	 printf("   printf: #4hhX9 '%#4.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #4hhX9 '%#4.9hhX'\n", uchar_a);
//	 printf("   printf: #-4hhX9 '%#-4.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #-4hhX9 '%#-4.9hhX'\n", uchar_a);
//	 printf("   printf: #04hhX9 '%#04.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #04hhX9 '%#04.9hhX'\n", uchar_a);
//	 printf("   printf: #9hhX9 '%#9.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #9hhX9 '%#9.9hhX'\n", uchar_a);
//	 printf("   printf: #-9hhX9 '%#-9.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #-9hhX9 '%#-9.9hhX'\n", uchar_a);
//	 printf("   printf: #09hhX9 '%#09.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #09hhX9 '%#09.9hhX'\n", uchar_a);
//	 printf("   printf: #20hhX9 '%#20.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #20hhX9 '%#20.9hhX'\n", uchar_a);
//	 printf("   printf: #-20hhX9 '%#-20.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #-20hhX9 '%#-20.9hhX'\n", uchar_a);
//	 printf("   printf: #020hhX9 '%#020.9hhX'\n", uchar_a);
//	 ft_printf("ft_printf: #020hhX9 '%#020.9hhX'\n", uchar_a);
//	 printf("   printf: lX9 '%.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: lX9 '%.9lX'\n", ulong_a);
//	 printf("   printf: 4lX9 '%4.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: 4lX9 '%4.9lX'\n", ulong_a);
//	 printf("   printf: -4lX9 '%-4.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: -4lX9 '%-4.9lX'\n", ulong_a);
//	 printf("   printf: 04lX9 '%04.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: 04lX9 '%04.9lX'\n", ulong_a);
//	 printf("   printf: 9lX9 '%9.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: 9lX9 '%9.9lX'\n", ulong_a);
//	 printf("   printf: -9lX9 '%-9.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: -9lX9 '%-9.9lX'\n", ulong_a);
//	 printf("   printf: 09lX9 '%09.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: 09lX9 '%09.9lX'\n", ulong_a);
//	 printf("   printf: 20lX9 '%20.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: 20lX9 '%20.9lX'\n", ulong_a);
//	 printf("   printf: -20lX9 '%-20.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: -20lX9 '%-20.9lX'\n", ulong_a);
//	 printf("   printf: 020lX9 '%020.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: 020lX9 '%020.9lX'\n", ulong_a);
//	 printf("   printf: #lX9 '%#.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #lX9 '%#.9lX'\n", ulong_a);
//	 printf("   printf: #4lX9 '%#4.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #4lX9 '%#4.9lX'\n", ulong_a);
//	 printf("   printf: #-4lX9 '%#-4.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #-4lX9 '%#-4.9lX'\n", ulong_a);
//	 printf("   printf: #04lX9 '%#04.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #04lX9 '%#04.9lX'\n", ulong_a);
//	 printf("   printf: #9lX9 '%#9.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #9lX9 '%#9.9lX'\n", ulong_a);
//	 printf("   printf: #-9lX9 '%#-9.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #-9lX9 '%#-9.9lX'\n", ulong_a);
//	 printf("   printf: #09lX9 '%#09.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #09lX9 '%#09.9lX'\n", ulong_a);
//	 printf("   printf: #20lX9 '%#20.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #20lX9 '%#20.9lX'\n", ulong_a);
//	 printf("   printf: #-20lX9 '%#-20.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #-20lX9 '%#-20.9lX'\n", ulong_a);
//	 printf("   printf: #020lX9 '%#020.9lX'\n", ulong_a);
//	 ft_printf("ft_printf: #020lX9 '%#020.9lX'\n", ulong_a);
//	 printf("   printf: llX9 '%.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: llX9 '%.9llX'\n", ullong_a);
//	 printf("   printf: 4llX9 '%4.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: 4llX9 '%4.9llX'\n", ullong_a);
//	 printf("   printf: -4llX9 '%-4.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: -4llX9 '%-4.9llX'\n", ullong_a);
//	 printf("   printf: 04llX9 '%04.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: 04llX9 '%04.9llX'\n", ullong_a);
//	 printf("   printf: 9llX9 '%9.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: 9llX9 '%9.9llX'\n", ullong_a);
//	 printf("   printf: -9llX9 '%-9.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: -9llX9 '%-9.9llX'\n", ullong_a);
//	 printf("   printf: 09llX9 '%09.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: 09llX9 '%09.9llX'\n", ullong_a);
//	 printf("   printf: 20llX9 '%20.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: 20llX9 '%20.9llX'\n", ullong_a);
//	 printf("   printf: -20llX9 '%-20.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: -20llX9 '%-20.9llX'\n", ullong_a);
//	 printf("   printf: 020llX9 '%020.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: 020llX9 '%020.9llX'\n", ullong_a);
//	 printf("   printf: #llX9 '%#.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #llX9 '%#.9llX'\n", ullong_a);
//	 printf("   printf: #4llX9 '%#4.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #4llX9 '%#4.9llX'\n", ullong_a);
//	 printf("   printf: #-4llX9 '%#-4.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #-4llX9 '%#-4.9llX'\n", ullong_a);
//	 printf("   printf: #04llX9 '%#04.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #04llX9 '%#04.9llX'\n", ullong_a);
//	 printf("   printf: #9llX9 '%#9.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #9llX9 '%#9.9llX'\n", ullong_a);
//	 printf("   printf: #-9llX9 '%#-9.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #-9llX9 '%#-9.9llX'\n", ullong_a);
//	 printf("   printf: #09llX9 '%#09.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #09llX9 '%#09.9llX'\n", ullong_a);
//	 printf("   printf: #20llX9 '%#20.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #20llX9 '%#20.9llX'\n", ullong_a);
//	 printf("   printf: #-20llX9 '%#-20.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #-20llX9 '%#-20.9llX'\n", ullong_a);
//	 printf("   printf: #020llX9 '%#020.9llX'\n", ullong_a);
//	 ft_printf("ft_printf: #020llX9 '%#020.9llX'\n", ullong_a);



	//  system("leaks ft_printf");
	return (0);
}
